/* Cornerstone — chapters 4–13, drawn from the 1689 LBCF (modern English).
   Pushed onto window.CH_MORE (loaded before data.js). */
(function () {
  const units = [
    // ── Chapter 4 · Of Creation ──────────────────────────────────────────
    { id: 4, chapter: 4, title: 'Of Creation', short: 'Creation', theme: 'navy',
      blurb: 'In the beginning, God made all things — and all of it very good.',
      lessons: [
        { id: '4-1', title: 'In the space of six days', icon: 'sun', questions: [
          { type: 'mc', prompt: 'In what span did God create the world and all things in it?',
            options: ['In the space of six days', 'Over countless unmeasured ages', 'In a single instant', 'The Confession does not say'],
            answer: 0, explain: '4.1 — God created the world, and all things in it, in the space of six days.' },
          { type: 'truefalse', statement: 'When God had finished his work of creation, all that he had made was very good.',
            answer: true, explain: '4.1 — and all very good, as in Genesis 1.' },
          { type: 'blank', before: 'God created all things to manifest the glory of his eternal power, wisdom, and',
            after: '.', options: ['goodness', 'sorrow', 'silence', 'distance'], answer: 'goodness',
            explain: '4.1 — for the manifestation of the glory of his eternal power, wisdom, and goodness.' },
          { type: 'mc', prompt: 'Why did God create all things?',
            options: ['To manifest the glory of his power, wisdom, and goodness', 'Because he was lonely', 'Because he needed servants', 'To learn what creatures would do'],
            answer: 0, explain: '4.1 — creation displays God\u2019s glory; he has no need of his creatures.' },
        ] },
        { id: '4-2', title: 'The crown of creation', icon: 'crown', questions: [
          { type: 'mc', prompt: 'After making all other creatures, how did God create man?',
            options: ['Male and female, with reasonable and immortal souls', 'As one being only, later divided', 'Without a soul, like the animals', 'Already fallen and sinful'],
            answer: 0, explain: '4.2 — he created man, male and female, with reasonable and immortal souls.' },
          { type: 'truefalse', statement: 'God made man in his own image, in knowledge, righteousness, and true holiness.',
            answer: true, explain: '4.2 — made after God\u2019s image, with his law written on their hearts.' },
          { type: 'blank', before: 'Besides the law written on their hearts, our first parents had the law of God written in their',
            after: '.', options: ['hearts', 'hands', 'books', 'stars'], answer: 'hearts',
            explain: '4.2 — having the law of God written in their hearts, with power to fulfil it.' },
          { type: 'mc', prompt: 'What particular command did God give Adam and Eve in the garden?',
            options: ['Not to eat of the tree of the knowledge of good and evil', 'To build an altar', 'To name the stars', 'To keep the seventh day only'],
            answer: 0, explain: '4.3 — a command not to eat of the tree of the knowledge of good and evil.' },
        ] },
      ] },

    // ── Chapter 5 · Of Divine Providence ─────────────────────────────────
    { id: 5, chapter: 5, title: 'Of Divine Providence', short: 'Providence', theme: 'gold',
      blurb: 'God upholds, directs, and governs all things — to the very least.',
      lessons: [
        { id: '5-1', title: 'He upholds all things', icon: 'compass', questions: [
          { type: 'mc', prompt: 'By what does God uphold, direct, dispose, and govern all creatures and things?',
            options: ['His wise and holy providence', 'Blind chance and fate', 'The free choices of creatures alone', 'The motion of the stars'],
            answer: 0, explain: '5.1 — God upholds and governs all things by his most wise and holy providence.' },
          { type: 'truefalse', statement: 'God\u2019s providence reaches even the smallest things, not only the greatest.',
            answer: true, explain: '5.1 — from the greatest even to the least.' },
          { type: 'passage', ref: 'Chapter 5, Paragraph 2',
            passage: 'Although in relation to the foreknowledge and decree of God, the first cause, all things come to pass immutably and infallibly; yet by the same providence he ordains them to fall out according to the nature of second causes, either necessarily, freely, or contingently.',
            question: 'How does God order things that come to pass?',
            options: ['Through second causes — necessarily, freely, or contingently', 'By bypassing all ordinary means', 'By forcing every creature against its nature', 'By leaving them entirely to chance'],
            answer: 0, explain: 'God\u2019s sure decree works through the real nature of second causes.' },
          { type: 'blank', before: 'God uses means in his providence, yet is free to work without, above, and',
            after: ' them.', options: ['against', 'beneath', 'beside', 'within'], answer: 'against',
            explain: '5.3 — he is free to work without, above, and against means at his pleasure.' },
        ] },
        { id: '5-2', title: 'Providence and evil', icon: 'shield', questions: [
          { type: 'truefalse', statement: 'God\u2019s providence extends even to sin, yet God is never the author of sin.',
            answer: true, explain: '5.4 — his providence reaches the fall and all sins, yet not as their author.' },
          { type: 'mc', prompt: 'Why does God sometimes leave his own children to temptation and the corruption of their hearts?',
            options: ['To chastise, humble, and draw them to depend more closely on him', 'Because he has abandoned them', 'Because his providence has failed', 'To make them lose their salvation'],
            answer: 0, explain: '5.5 — for their chastisement, humbling, and to raise them to a closer dependence.' },
          { type: 'mc', prompt: 'How does God\u2019s providence relate to his church?',
            options: ['He takes care of it in a special manner, ordering all things for its good', 'He governs it the same as the rest of the world', 'He leaves it to its own devices', 'He withdraws his care once it is gathered'],
            answer: 0, explain: '5.7 — providence takes care of his church in a most special manner.' },
          { type: 'truefalse', statement: 'God hardens the wicked, justly withholding grace they had abused.',
            answer: true, explain: '5.6 — from the righteous Judge, the wicked are blinded and hardened.' },
        ] },
      ] },

    // ── Chapter 6 · Of the Fall of Man, of Sin, and of the Punishment ────
    { id: 6, chapter: 6, title: 'Of the Fall of Man & Sin', short: 'The Fall', theme: 'navy',
      blurb: 'How sin entered the world — and what it did to us all.',
      lessons: [
        { id: '6-1', title: 'How sin entered', icon: 'flame', questions: [
          { type: 'truefalse', statement: 'God created man upright; the fall came by our first parents\u2019 own sin.',
            answer: true, explain: '6.1 — God created man upright; they sinned by eating the forbidden fruit.' },
          { type: 'mc', prompt: 'How did our first parents fall into sin?',
            options: ['By eating the forbidden fruit, being seduced by Satan', 'By a flaw God built into them', 'By an accident outside their will', 'They never actually fell'],
            answer: 0, explain: '6.1 — seduced by Satan, they ate; God permitting it for his own glory.' },
          { type: 'blank', before: 'By their sin, our first parents fell from their original',
            after: '.', options: ['righteousness', 'wealth', 'memory', 'strength'], answer: 'righteousness',
            explain: '6.2 — they fell from original righteousness, and became dead in sin.' },
          { type: 'mc', prompt: 'Did Adam\u2019s sin affect only himself?',
            options: ['No — as the root of mankind, the guilt was imputed and corrupt nature conveyed to all', 'Yes, it touched no one else', 'Only his immediate children', 'Only those who imitate him'],
            answer: 0, explain: '6.3 — they being the root, guilt was imputed and corrupted nature conveyed to all their posterity.' },
        ] },
        { id: '6-2', title: 'Original corruption', icon: 'seal', questions: [
          { type: 'truefalse', statement: 'From this original corruption we are by nature inclined to all evil and disabled to all spiritual good.',
            answer: true, explain: '6.4 — we are utterly indisposed, disabled, and opposite to all good, and inclined to all evil.' },
          { type: 'mc', prompt: 'What does the Confession say about corruption in those who are born again?',
            options: ['It remains during this life, even in the regenerate', 'It is entirely removed at conversion', 'It never existed in them', 'It grows stronger as they mature'],
            answer: 0, explain: '6.5 — this corruption of nature remains in the regenerate during this life.' },
          { type: 'blank', before: 'Every sin, both original and actual, brings guilt upon the sinner, making him subject to the wrath of God and the curse of the',
            after: '.', options: ['law', 'church', 'world', 'flesh'], answer: 'law',
            explain: '6.x — sin makes us subject to the wrath of God and the curse of the law, and so to death.' },
          { type: 'mc', prompt: 'What does sin make us subject to?',
            options: ['The wrath of God, the curse of the law, and death', 'A temporary discomfort only', 'Nothing, if we mean well', 'Merely the judgment of other people'],
            answer: 0, explain: 'Sin brings guilt, the wrath of God, and all spiritual, temporal, and eternal miseries.' },
        ] },
      ] },

    // ── Chapter 7 · Of God's Covenant ────────────────────────────────────
    { id: 7, chapter: 7, title: "Of God's Covenant", short: 'The Covenant', theme: 'gold',
      blurb: 'God stoops to bind himself to his people by way of covenant.',
      lessons: [
        { id: '7-1', title: 'God stoops to covenant', icon: 'scroll', questions: [
          { type: 'mc', prompt: 'Why was a covenant needed for man to enjoy God as his blessedness?',
            options: ['The distance between God and creature is so great it required God\u2019s voluntary condescension', 'Man demanded a contract', 'God needed something from man', 'Angels arranged it'],
            answer: 0, explain: '7.1 — the distance is so great that man could never enjoy God except by some voluntary condescension, expressed by way of covenant.' },
          { type: 'truefalse', statement: 'Man could have earned eternal blessedness with God apart from any covenant.',
            answer: false, explain: '7.1 — only by God\u2019s voluntary condescension, by way of covenant.' },
          { type: 'blank', before: 'Having fallen under the curse of the law, the Lord was pleased to make a covenant of',
            after: '.', options: ['grace', 'works', 'silence', 'fear'], answer: 'grace',
            explain: '7.2 — the Lord made a covenant of grace, freely offering life and salvation by Christ.' },
          { type: 'mc', prompt: 'In the covenant of grace, what does God freely offer sinners?',
            options: ['Life and salvation by Jesus Christ, requiring faith in him', 'A second chance to keep the law', 'Wealth and ease', 'Salvation earned by good works'],
            answer: 0, explain: '7.2 — he freely offers sinners life and salvation by Jesus Christ, requiring faith.' },
        ] },
        { id: '7-2', title: 'Revealed by steps', icon: 'book', questions: [
          { type: 'truefalse', statement: 'The covenant of grace was first revealed in the promise of salvation by the seed of the woman.',
            answer: true, explain: '7.3 — first revealed to Adam in the promise of salvation by the seed of the woman.' },
          { type: 'mc', prompt: 'How was the covenant of grace made known across the ages?',
            options: ['By further steps, until its full discovery in the New Testament', 'All at once to Moses', 'Only after Christ\u2019s ascension', 'It was never fully revealed'],
            answer: 0, explain: '7.3 — carried on by farther steps until the full discovery was completed in the New Testament.' },
          { type: 'type', prompt: 'The covenant of grace requires of sinners ________ in Jesus Christ that they may be saved.',
            accept: ['faith', 'belief'], answer: 'faith',
            explain: '7.2 — requiring faith in Christ that they may be saved.' },
          { type: 'mc', prompt: 'On whom does the whole covenant of grace rest?',
            options: ['Jesus Christ', 'The obedience of the believer', 'The faithfulness of the church', 'The works of the law'],
            answer: 0, explain: 'Salvation in the covenant is by Jesus Christ alone.' },
        ] },
      ] },

    // ── Chapter 8 · Of Christ the Mediator ───────────────────────────────
    { id: 8, chapter: 8, title: 'Of Christ the Mediator', short: 'The Mediator', theme: 'navy',
      blurb: 'God and man in one person — our prophet, priest, and king.',
      lessons: [
        { id: '8-1', title: 'The one Mediator', icon: 'seal', questions: [
          { type: 'mc', prompt: 'Whom did it please God to choose as the Mediator between God and man?',
            options: ['The Lord Jesus, his only begotten Son', 'The angel Gabriel', 'Moses the lawgiver', 'The high priest of Israel'],
            answer: 0, explain: '8.1 — God chose the Lord Jesus, his only begotten Son, to be the Mediator.' },
          { type: 'match', prompt: 'Match each of Christ\u2019s mediatorial offices to its work.',
            pairs: [
              { a: 'Prophet', b: 'reveals the will of God for our salvation' },
              { a: 'Priest', b: 'offers himself and intercedes for his people' },
              { a: 'King', b: 'rules, defends, and subdues his people to himself' },
            ] },
          { type: 'truefalse', statement: 'Christ is the head and Saviour of the church, the heir of all things, and judge of the world.',
            answer: true, explain: '8.1 — given to be head and Saviour, heir of all things, and judge of the world.' },
          { type: 'blank', before: 'Christ holds the threefold office of prophet, priest, and',
            after: '.', options: ['king', 'scribe', 'angel', 'elder'], answer: 'king',
            explain: '8.1 — prophet, priest, and king.' },
        ] },
        { id: '8-2', title: 'Truly God and truly man', icon: 'triangle', questions: [
          { type: 'mc', prompt: 'What does the Confession affirm about Christ\u2019s person?',
            options: ['Two whole, perfect, distinct natures — God and man — in one person', 'One nature, partly God and partly man', 'A man specially adopted by God', 'God only appearing to be a man'],
            answer: 0, explain: '8.2 — two whole, perfect, distinct natures inseparably joined in one person.' },
          { type: 'truefalse', statement: 'In Christ the two natures were mixed and confused into a third kind of nature.',
            answer: false, explain: '8.2 — joined without conversion, composition, or confusion.' },
          { type: 'passage', ref: 'Chapter 8, Paragraph 2',
            passage: 'So that two whole, perfect, and distinct natures were inseparably joined together in one person, without conversion, composition, or confusion; which person is very God and very man, yet one Christ, the only mediator between God and man.',
            question: 'How are the two natures of Christ joined?',
            options: ['Inseparably in one person, without conversion, composition, or confusion', 'Loosely, so they can act apart', 'Blended into a single new nature', 'Only in appearance'],
            answer: 0, explain: 'One person, two natures, unmixed and undivided.' },
          { type: 'type', prompt: 'The Confession says Christ is very God and very ________.',
            accept: ['man'], answer: 'man', explain: '8.2 — very God and very man, yet one Christ.' },
        ] },
      ] },

    // ── Chapter 9 · Of Free Will ─────────────────────────────────────────
    { id: 9, chapter: 9, title: 'Of Free Will', short: 'Free Will', theme: 'gold',
      blurb: 'What the will can and cannot do — before grace, and after.',
      lessons: [
        { id: '9-1', title: 'Natural liberty', icon: 'compass', questions: [
          { type: 'mc', prompt: 'What has God given to man\u2019s will by nature?',
            options: ['Natural liberty — it is neither forced nor determined to good or evil', 'No freedom whatsoever', 'A fixed bent toward good only', 'The power to save itself'],
            answer: 0, explain: '9.1 — God has endued man\u2019s will with natural liberty.' },
          { type: 'truefalse', statement: 'In his state of innocence, man had freedom and power to will and do what is good.',
            answer: true, explain: '9.2 — man had freedom and power to will and to do that which was good.' },
          { type: 'blank', before: 'By his fall into sin, man has wholly lost all ability of will toward any spiritual',
            after: '.', options: ['good', 'pride', 'labour', 'sorrow'], answer: 'good',
            explain: '9.3 — man has wholly lost all ability of will to any spiritual good accompanying salvation.' },
          { type: 'mc', prompt: 'Can fallen man, by his own strength, convert himself or prepare himself for conversion?',
            options: ['No — being dead in sin, he cannot', 'Yes, if he tries hard enough', 'Yes, with a little help', 'Only the wise can'],
            answer: 0, explain: '9.3 — being dead in sin, he is not able by his own strength to convert himself.' },
        ] },
        { id: '9-2', title: 'Freed by grace', icon: 'star', questions: [
          { type: 'truefalse', statement: 'When God converts a sinner, he frees him from his natural bondage to sin and enables him to will good.',
            answer: true, explain: '9.4 — God frees him from his natural bondage and enables him freely to will and do good.' },
          { type: 'mc', prompt: 'When is the will made perfectly and only free to good?',
            options: ['In the state of glory alone', 'At the moment of conversion', 'After enough effort in this life', 'It never is'],
            answer: 0, explain: '9.5 — the will is made perfectly and immutably free to good alone in the state of glory.' },
          { type: 'blank', before: 'Even after conversion, a believer still does evil because of remaining',
            after: '.', options: ['corruption', 'freedom', 'wisdom', 'glory'], answer: 'corruption',
            explain: '9.4 — by reason of remaining corruption, he does not perfectly will the good.' },
          { type: 'mc', prompt: 'The converted will is freed so that it now —',
            options: ['Freely wills and does that which is spiritually good', 'Loses all liberty', 'Is forced against itself', 'Becomes sinless at once'],
            answer: 0, explain: '9.4 — enabled freely to will and to do that which is spiritually good.' },
        ] },
      ] },

    // ── Chapter 10 · Of Effectual Calling ────────────────────────────────
    { id: 10, chapter: 10, title: 'Of Effectual Calling', short: 'The Call', theme: 'navy',
      blurb: 'How God draws dead sinners to life by his Word and Spirit.',
      lessons: [
        { id: '10-1', title: 'Called by Word and Spirit', icon: 'flame', questions: [
          { type: 'mc', prompt: 'How does God bring those he predestined to grace and salvation?',
            options: ['He effectually calls them by his Word and Spirit', 'By the persuasion of preachers alone', 'By their own first decision', 'By outward ceremony'],
            answer: 0, explain: '10.1 — God effectually calls them by his Word and Spirit, out of sin and death.' },
          { type: 'truefalse', statement: 'In effectual calling, God takes away the heart of stone and gives a heart of flesh.',
            answer: true, explain: '10.1 — taking away the heart of stone, giving a heart of flesh, renewing the will.' },
          { type: 'blank', before: 'Effectual calling is of God\u2019s free and special',
            after: ' alone.', options: ['grace', 'choice', 'reward', 'law'], answer: 'grace',
            explain: '10.2 — this calling is of God\u2019s free and special grace alone.' },
          { type: 'mc', prompt: 'Does effectual calling depend on anything foreseen in the person?',
            options: ['No — it flows from grace alone, not from anything foreseen', 'Yes, on their foreseen faith', 'Yes, on their good works', 'Yes, on their family line'],
            answer: 0, explain: '10.2 — not from anything at all foreseen in man, who is altogether passive therein.' },
        ] },
        { id: '10-2', title: 'Grace that draws', icon: 'seal', questions: [
          { type: 'truefalse', statement: 'Those effectually called come to Christ most freely, being made willing by his grace.',
            answer: true, explain: '10.1 — yet so as they come most freely, being made willing by his grace.' },
          { type: 'mc', prompt: 'What does the Confession say of elect infants dying in infancy?',
            options: ['They are regenerated and saved by Christ through the Spirit', 'They cannot be saved', 'They must first be baptized', 'Their state is unknown'],
            answer: 0, explain: '10.3 — elect infants dying in infancy are regenerated and saved by Christ.' },
          { type: 'mc', prompt: 'Can those not elected, though they hear the Word, be saved?',
            options: ['No — not being effectually called, they cannot be saved', 'Yes, if they try hard', 'Yes, by their sincerity', 'Yes, automatically'],
            answer: 0, explain: '10.4 — others not elected, though called by the ministry of the Word, cannot be saved.' },
          { type: 'blank', before: 'God enlightens their minds, renews their wills, and draws them to Jesus',
            after: '.', options: ['Christ', 'Moses', 'David', 'Peter'], answer: 'Christ',
            explain: '10.1 — effectually drawing them to Jesus Christ.' },
        ] },
      ] },

    // ── Chapter 11 · Of Justification ────────────────────────────────────
    { id: 11, chapter: 11, title: 'Of Justification', short: 'Justification', theme: 'gold',
      blurb: 'How a guilty sinner is counted righteous before God.',
      lessons: [
        { id: '11-1', title: 'Declared righteous', icon: 'seal', questions: [
          { type: 'mc', prompt: 'How does God justify those he effectually calls?',
            options: ['By pardoning their sins and accounting them righteous, for Christ\u2019s sake alone', 'By making them sinless in themselves', 'By weighing their good against their bad', 'By overlooking sin without a remedy'],
            answer: 0, explain: '11.1 — not by infusing righteousness, but by pardoning sin and accounting them righteous.' },
          { type: 'truefalse', statement: 'God justifies sinners by infusing righteousness into them so they become righteous in themselves.',
            answer: false, explain: '11.1 — not by infusing righteousness, but by imputing Christ\u2019s righteousness.' },
          { type: 'blank', before: 'We are justified by imputing the obedience and satisfaction of',
            after: ' to us.', options: ['Christ', 'the saints', 'the church', 'ourselves'], answer: 'Christ',
            explain: '11.1 — by imputing Christ\u2019s active obedience and passive satisfaction to them.' },
          { type: 'mc', prompt: 'What is faith\u2019s role in justification?',
            options: ['It is the alone instrument by which we receive and rest on Christ', 'It is the righteousness that earns acceptance', 'It is a good work that merits pardon', 'It plays no part at all'],
            answer: 0, explain: '11.2 — faith is the alone instrument of justification.' },
        ] },
        { id: '11-2', title: 'Faith alone, yet not alone', icon: 'star', questions: [
          { type: 'truefalse', statement: 'The faith that justifies is never alone, but always works by love.',
            answer: true, explain: '11.2 — yet it is not alone, but works by love.' },
          { type: 'mc', prompt: 'What did Christ do to satisfy God\u2019s justice for the justified?',
            options: ['By his obedience and death he fully discharged their debt and satisfied justice', 'He merely set a good example', 'He left the debt for them to pay', 'He paid only part of it'],
            answer: 0, explain: '11.3 — Christ fully discharged the debt and made proper, real satisfaction to God\u2019s justice.' },
          { type: 'type', prompt: 'A sinner is justified by grace through faith ________ — not by works.',
            accept: ['alone', 'only'], answer: 'alone', explain: '11.1\u201311.2 — by faith alone, apart from works.' },
          { type: 'mc', prompt: 'Can the justified ever fall from the state of justification?',
            options: ['No — though they may fall under God\u2019s fatherly displeasure, they are never cast out', 'Yes, they can lose it by sin', 'Yes, if their faith weakens', 'Yes, at God\u2019s whim'],
            answer: 0, explain: '11.5 — they can never fall from the state of justification.' },
        ] },
      ] },

    // ── Chapter 12 · Of Adoption ─────────────────────────────────────────
    { id: 12, chapter: 12, title: 'Of Adoption', short: 'Adoption', theme: 'navy',
      blurb: 'Justified sinners are taken in as the very children of God.',
      lessons: [
        { id: '12-1', title: 'Children of God', icon: 'sun', questions: [
          { type: 'mc', prompt: 'All those who are justified, God makes partakers of the grace of —',
            options: ['Adoption', 'Ordination', 'Coronation', 'Reputation'],
            answer: 0, explain: '12.1 — God vouchsafes to make them partakers of the grace of adoption.' },
          { type: 'truefalse', statement: 'In adoption, believers are taken into the number of God\u2019s children and receive the Spirit of adoption.',
            answer: true, explain: '12.1 — enjoying the liberties and privileges of children, having the Spirit of adoption.' },
          { type: 'blank', before: 'Having the Spirit of adoption, believers have access to the throne of grace with',
            after: '.', options: ['boldness', 'dread', 'doubt', 'silence'], answer: 'boldness',
            explain: '12.1 — they have access to the throne of grace with boldness, crying Abba, Father.' },
          { type: 'mc', prompt: 'How does God treat his adopted children?',
            options: ['He pities, protects, provides for, and chastens them as a Father, never casting them off', 'He keeps them at a distance', 'He treats them as hired servants', 'He adopts and then forgets them'],
            answer: 0, explain: '12.1 — pitied, protected, provided for, and chastened, yet never cast off.' },
        ] },
        { id: '12-2', title: 'The privileges of sons', icon: 'crown', questions: [
          { type: 'truefalse', statement: 'God\u2019s adopted children are sealed to the day of redemption and inherit the promises.',
            answer: true, explain: '12.1 — sealed to the day of redemption, and inherit the promises as heirs of salvation.' },
          { type: 'type', prompt: 'By the Spirit of adoption the children of God cry, \u201c________, Father.\u201d',
            accept: ['abba'], answer: 'Abba', explain: '12.1 — crying Abba, Father (Romans 8:15).' },
          { type: 'mc', prompt: 'The adopted are heirs of —',
            options: ['Everlasting salvation', 'Earthly riches only', 'A temporary blessing', 'Nothing certain'],
            answer: 0, explain: '12.1 — as heirs of everlasting salvation.' },
        ] },
      ] },

    // ── Chapter 13 · Of Sanctification ───────────────────────────────────
    { id: 13, chapter: 13, title: 'Of Sanctification', short: 'Sanctification', theme: 'gold',
      blurb: 'The lifelong work of being made holy, by the Word and Spirit.',
      lessons: [
        { id: '13-1', title: 'Made holy', icon: 'flame', questions: [
          { type: 'mc', prompt: 'Through what are believers sanctified?',
            options: ['Christ\u2019s death and resurrection, by his Word and Spirit dwelling in them', 'Their own willpower', 'Religious ritual alone', 'The passage of time'],
            answer: 0, explain: '13.1 — sanctified by the virtue of Christ\u2019s death and resurrection, by his Word and Spirit.' },
          { type: 'truefalse', statement: 'In sanctification the dominion of sin is destroyed and its lusts are weakened and mortified.',
            answer: true, explain: '13.1 — the dominion of the whole body of sin is destroyed, its lusts mortified.' },
          { type: 'blank', before: 'Sanctification is throughout the whole man, yet it is',
            after: ' in this life.', options: ['imperfect', 'complete', 'optional', 'invisible'], answer: 'imperfect',
            explain: '13.2 — this sanctification is imperfect in this life; remnants of corruption remain.' },
          { type: 'mc', prompt: 'What remains in the believer even as sanctification grows?',
            options: ['Remnants of corruption, so a continual war remains', 'Nothing — sin is wholly gone', 'A neutral, sinless calm', 'Only outward struggles'],
            answer: 0, explain: '13.2 — there remains a continual and irreconcilable war, the flesh against the Spirit.' },
        ] },
        { id: '13-2', title: 'The continual war', icon: 'shield', questions: [
          { type: 'truefalse', statement: 'There is a continual war in the believer — the flesh lusting against the Spirit.',
            answer: true, explain: '13.2 — the flesh lusts against the Spirit, and the Spirit against the flesh.' },
          { type: 'mc', prompt: 'In this war between flesh and Spirit, what finally happens for the believer?',
            options: ['Through strength from Christ, the regenerate part overcomes', 'The flesh wins in the end', 'It ends in a permanent stalemate', 'The believer must give up'],
            answer: 0, explain: '13.3 — through the continual supply of strength from Christ, the regenerate part overcomes.' },
          { type: 'blank', before: 'The saints grow in grace, perfecting holiness in the',
            after: ' of God.', options: ['fear', 'sight', 'house', 'name'], answer: 'fear',
            explain: '13.3 — growing in grace, perfecting holiness in the fear of God.' },
          { type: 'type', prompt: 'In the believer, the flesh lusts against the ________.',
            accept: ['spirit'], answer: 'Spirit', explain: '13.2 — the flesh against the Spirit (Galatians 5:17).' },
        ] },
      ] },
  ];

  window.CH_MORE = (window.CH_MORE || []).concat(units);
})();
