/* Cornerstone — chapters 14–23, drawn from the 1689 LBCF (modern English).
   Pushed onto window.CH_MORE (loaded before data.js). */
(function () {
  const units = [
    // ── Chapter 14 · Of Saving Faith ─────────────────────────────────────
    { id: 14, chapter: 14, title: 'Of Saving Faith', short: 'Saving Faith', theme: 'navy',
      blurb: 'The God-given faith by which the elect believe to the saving of their souls.',
      lessons: [
        { id: '14-1', title: 'The gift of faith', icon: 'seal', questions: [
          { type: 'mc', prompt: 'Where does saving faith come from?',
            options: ['It is the work of the Spirit of Christ in the heart', 'We generate it by our own effort', 'It is inherited from believing parents', 'It comes from religious upbringing alone'],
            answer: 0, explain: '14.1 — the grace of faith is the work of the Spirit of Christ in the heart.' },
          { type: 'truefalse', statement: 'Saving faith is something we produce in ourselves by our own strength.',
            answer: false, explain: '14.1 — it is the work of the Spirit, not of ourselves.' },
          { type: 'blank', before: 'The grace of faith is the work of the',
            after: ' of Christ in the heart.', options: ['Spirit', 'law', 'church', 'flesh'], answer: 'Spirit',
            explain: '14.1 — wrought by the Spirit of Christ.' },
          { type: 'mc', prompt: 'By what means is faith ordinarily wrought?',
            options: ['By the ministry of the Word', 'By visions and dreams', 'By human persuasion only', 'By outward ritual'],
            answer: 0, explain: '14.1 — ordinarily wrought by the ministry of the Word.' },
        ] },
        { id: '14-2', title: 'What faith does', icon: 'star', questions: [
          { type: 'mc', prompt: 'What are the principal acts of saving faith?',
            options: ['Accepting, receiving, and resting on Christ alone for salvation', 'Keeping a list of rules', 'Trusting one\u2019s own sincerity', 'Hoping for the best'],
            answer: 0, explain: '14.2 — the principal acts are accepting, receiving, and resting upon Christ alone.' },
          { type: 'truefalse', statement: 'Saving faith may be weak or strong, often assailed, yet in the end gains the victory.',
            answer: true, explain: '14.3 — this faith is different in degrees, may be assailed and weakened, yet gets the victory.' },
          { type: 'blank', before: 'Faith grows up in many to the attainment of a full',
            after: ' through Christ.', options: ['assurance', 'reward', 'comfort', 'silence'], answer: 'assurance',
            explain: '14.3 — growing up to the attainment of a full assurance through Christ.' },
          { type: 'type', prompt: 'The author and finisher of our faith is ________.',
            accept: ['christ', 'jesus', 'jesus christ'], answer: 'Christ',
            explain: '14.3 — Christ, the author and finisher of our faith (Hebrews 12:2).' },
        ] },
      ] },

    // ── Chapter 15 · Of Repentance Unto Life and Salvation ───────────────
    { id: 15, chapter: 15, title: 'Of Repentance Unto Life', short: 'Repentance', theme: 'gold',
      blurb: 'The saving grace of turning from sin to God.',
      lessons: [
        { id: '15-1', title: 'A turning of the heart', icon: 'flame', questions: [
          { type: 'mc', prompt: 'Saving repentance is a grace by which a sinner —',
            options: ['Grieves for and hates his sins, and turns from them all to God', 'Merely feels sorry he was caught', 'Promises to do better on his own', 'Performs acts of penance to earn pardon'],
            answer: 0, explain: '15.3 — he so grieves for and hates his sins as to turn from them all unto God.' },
          { type: 'truefalse', statement: 'True repentance includes purposing to walk with God in all the ways of his commandments.',
            answer: true, explain: '15.3 — purposing and endeavouring to walk with God in all the ways of his commandments.' },
          { type: 'blank', before: 'By repentance a sinner turns from all his sins unto',
            after: '.', options: ['God', 'the law', 'the world', 'himself'], answer: 'God',
            explain: '15.3 — turning from them all unto God.' },
          { type: 'mc', prompt: 'What moves a sinner to true repentance?',
            options: ['Being made aware of the many evils of his sin, and trusting Christ for mercy', 'Fear of other people', 'A wish to look respectable', 'Nothing in particular'],
            answer: 0, explain: '15.3 — being made sensible by the Spirit of the manifold evils of his sin, he humbles himself by faith in Christ.' },
        ] },
        { id: '15-2', title: 'A lifelong repentance', icon: 'compass', questions: [
          { type: 'truefalse', statement: 'Repentance is to be continued throughout the whole course of our lives.',
            answer: true, explain: '15.4 — repentance is to be continued through the whole course of our lives.' },
          { type: 'mc', prompt: 'Should believers content themselves with a general repentance only?',
            options: ['No — they ought to repent of their particular known sins, particularly', 'Yes, a general sorrow is enough', 'No repentance is needed after conversion', 'Only public sins need repenting'],
            answer: 0, explain: '15.4 — it is every person\u2019s duty to repent of his particular known sins, particularly.' },
          { type: 'mc', prompt: 'What has God provided for believers who fall into great sins?',
            options: ['That they be renewed through repentance unto salvation', 'That they lose their salvation', 'That they earn pardon by penance', 'Nothing — they are cast off'],
            answer: 0, explain: '15.2 — in the covenant of grace God has provided that believers who fall are renewed through repentance unto salvation.' },
          { type: 'blank', before: 'God has mercifully provided that believers who sin and fall be renewed through',
            after: ' unto salvation.', options: ['repentance', 'penance', 'merit', 'silence'], answer: 'repentance',
            explain: '15.2 — renewed through repentance unto salvation.' },
        ] },
      ] },

    // ── Chapter 16 · Of Good Works ───────────────────────────────────────
    { id: 16, chapter: 16, title: 'Of Good Works', short: 'Good Works', theme: 'navy',
      blurb: 'What good works are, where they come from, and how God receives them.',
      lessons: [
        { id: '16-1', title: 'What good works are', icon: 'seal', questions: [
          { type: 'mc', prompt: 'What alone are truly good works?',
            options: ['Only those things God has commanded in his holy Word', 'Whatever seems kind to us', 'Whatever the church invents', 'Anything done with good intentions'],
            answer: 0, explain: '16.1 — good works are only such as God has commanded in his holy Word.' },
          { type: 'truefalse', statement: 'Works devised by men out of good intentions, without God\u2019s warrant, are truly good works.',
            answer: false, explain: '16.1 — not such as are devised by men out of blind zeal or any pretence of good intention.' },
          { type: 'blank', before: 'Good works are the fruits and evidences of a true and living',
            after: '.', options: ['faith', 'wealth', 'wisdom', 'name'], answer: 'faith',
            explain: '16.2 — good works are the fruits and evidences of a true and lively faith.' },
          { type: 'mc', prompt: 'Where does the believer\u2019s ability to do good works come from?',
            options: ['Wholly from the Spirit of Christ', 'From their own natural strength', 'From their upbringing', 'From the example of others'],
            answer: 0, explain: '16.3 — their ability to do good works is wholly from the Spirit of Christ.' },
        ] },
        { id: '16-2', title: 'Accepted in Christ', icon: 'star', questions: [
          { type: 'truefalse', statement: 'By our best works we can merit the pardon of sin or eternal life from God.',
            answer: false, explain: '16.5 — we cannot by our best works merit pardon of sin or eternal life.' },
          { type: 'mc', prompt: 'How are believers\u2019 imperfect good works accepted by God?',
            options: ['In Christ — God looks on them in his Son and accepts them', 'Only if they are perfect', 'They are not accepted at all', 'By weighing them against their sins'],
            answer: 0, explain: '16.6 — believers\u2019 good works are accepted in Christ.' },
          { type: 'mc', prompt: 'Can those who reach great heights of obedience do more than God requires?',
            options: ['No — they cannot do more than is required (no supererogation)', 'Yes, and store up extra merit', 'Yes, for others to use', 'The Confession leaves it open'],
            answer: 0, explain: '16.4 — they cannot, by their utmost, do supererogatory works beyond what God requires.' },
          { type: 'blank', before: 'Works done by unregenerate men, though of use, cannot',
            after: ' God.', options: ['please', 'anger', 'surprise', 'help'], answer: 'please',
            explain: '16.7 — works done by unregenerate men, though materially good, cannot please God.' },
        ] },
      ] },

    // ── Chapter 17 · Of the Perseverance of the Saints ───────────────────
    { id: 17, chapter: 17, title: 'Of the Perseverance of the Saints', short: 'Perseverance', theme: 'gold',
      blurb: 'Those God truly saves, he keeps to the very end.',
      lessons: [
        { id: '17-1', title: 'Kept to the end', icon: 'shield', questions: [
          { type: 'mc', prompt: 'Can those God has accepted and sanctified finally fall away and be lost?',
            options: ['No — they shall persevere to the end and be eternally saved', 'Yes, they may lose salvation', 'Only the strong persevere', 'It cannot be known'],
            answer: 0, explain: '17.1 — they can neither totally nor finally fall, but shall persevere to the end.' },
          { type: 'truefalse', statement: 'The saints can neither totally nor finally fall from the state of grace.',
            answer: true, explain: '17.1 — they shall certainly persevere therein to the end.' },
          { type: 'blank', before: 'Perseverance depends not on the saints\u2019 own free will, but on the immutability of the decree of',
            after: '.', options: ['election', 'nature', 'fortune', 'works'], answer: 'election',
            explain: '17.2 — it depends on the immutability of the decree of election.' },
          { type: 'mc', prompt: 'On what does the saints\u2019 perseverance rest?',
            options: ['God\u2019s decree and love, Christ\u2019s merit and intercession, and the Spirit within them', 'Their own determination', 'Their church membership', 'Their good record'],
            answer: 0, explain: '17.2 — on election, God\u2019s love, Christ\u2019s merit and intercession, and the abiding Spirit and seed of God.' },
        ] },
        { id: '17-2', title: 'They may stumble, not fall', icon: 'flame', questions: [
          { type: 'truefalse', statement: 'Believers may, through temptation, fall into grievous sins and grieve the Spirit.',
            answer: true, explain: '17.3 — they may fall into grievous sins, and grieve the Spirit of God.' },
          { type: 'mc', prompt: 'When believers fall into sin, what is the outcome for the truly saved?',
            options: ['They incur God\u2019s displeasure but renew their repentance and are kept', 'They lose their salvation', 'They are cast off forever', 'Nothing changes at all'],
            answer: 0, explain: '17.3 — they incur God\u2019s displeasure, yet renew their repentance and are preserved.' },
          { type: 'blank', before: 'The perseverance of the saints rests on the merit and intercession of',
            after: '.', options: ['Christ', 'the church', 'the saints', 'angels'], answer: 'Christ',
            explain: '17.2 — upon the merit and intercession of Jesus Christ.' },
          { type: 'type', prompt: 'Those whom God has truly saved shall ________ to the end.',
            accept: ['persevere', 'endure', 'continue'], answer: 'persevere',
            explain: '17.1 — they shall certainly persevere to the end.' },
        ] },
      ] },

    // ── Chapter 18 · Of the Assurance of Grace and Salvation ─────────────
    { id: 18, chapter: 18, title: 'Of the Assurance of Grace', short: 'Assurance', theme: 'navy',
      blurb: 'How a believer may be truly and certainly assured of salvation.',
      lessons: [
        { id: '18-1', title: 'Sure and certain', icon: 'sun', questions: [
          { type: 'mc', prompt: 'Can those who truly believe be certainly assured they are in a state of grace?',
            options: ['Yes — they may be certainly assured', 'No, never with any certainty', 'Only the clergy may be', 'Only on their deathbed'],
            answer: 0, explain: '18.1 — they may in this life be certainly assured that they are in the state of grace.' },
          { type: 'truefalse', statement: 'True assurance is merely a hopeful guess that may well be mistaken.',
            answer: false, explain: '18.2 — not a bare conjectural persuasion, but an infallible assurance of faith.' },
          { type: 'blank', before: 'True assurance is founded on the blood and righteousness of',
            after: '.', options: ['Christ', 'the saints', 'the law', 'man'], answer: 'Christ',
            explain: '18.2 — founded on the blood and righteousness of Christ revealed in the gospel.' },
          { type: 'mc', prompt: 'On what is true assurance founded?',
            options: ['Christ\u2019s righteousness, the inward evidence of graces, and the witness of the Spirit', 'A feeling that comes and goes', 'The praise of others', 'One\u2019s own merits'],
            answer: 0, explain: '18.2 — on Christ\u2019s blood and righteousness, the evidence of graces, and the Spirit of adoption.' },
        ] },
        { id: '18-2', title: 'Shaken but not lost', icon: 'shield', questions: [
          { type: 'truefalse', statement: 'Assurance belongs to the essence of faith, so a true believer always has it from the first.',
            answer: false, explain: '18.3 — assurance is not of the essence of faith; a believer may wait long for it.' },
          { type: 'mc', prompt: 'Can a believer\u2019s assurance be shaken or diminished?',
            options: ['Yes — by negligence, sin, or temptation, yet the seed of God remains', 'No, once given it never changes', 'Only false assurance is shaken', 'It is destroyed entirely by any sin'],
            answer: 0, explain: '18.4 — assurance may be shaken, diminished, and intermitted, yet not utterly lost.' },
          { type: 'blank', before: 'Even when assurance is shaken, the believer is never utterly destitute of the',
            after: ' of God.', options: ['seed', 'wrath', 'memory', 'voice'], answer: 'seed',
            explain: '18.4 — they are never utterly destitute of that seed of God and life of faith.' },
          { type: 'mc', prompt: 'Before obtaining assurance, a true believer —',
            options: ['May wait long and wrestle with many difficulties', 'Always has it instantly', 'Can never have it at all', 'Must earn it by works'],
            answer: 0, explain: '18.3 — a true believer may wait long, and conflict with many difficulties, before he attains it.' },
        ] },
      ] },

    // ── Chapter 19 · Of the Law of God ───────────────────────────────────
    { id: 19, chapter: 19, title: 'Of the Law of God', short: 'The Law', theme: 'gold',
      blurb: 'The moral law, the ceremonial, the judicial — and their use today.',
      lessons: [
        { id: '19-1', title: 'The moral law', icon: 'scroll', questions: [
          { type: 'mc', prompt: 'What did God give Adam as a rule of obedience?',
            options: ['A law of universal obedience, written on his heart', 'Only the command about the tree', 'A set of ceremonies', 'No law at all'],
            answer: 0, explain: '19.1 — God gave Adam a law of universal obedience written in his heart.' },
          { type: 'truefalse', statement: 'After the fall, the moral law continued to be a perfect rule of righteousness.',
            answer: true, explain: '19.2 — this law continued a perfect rule of righteousness after the fall.' },
          { type: 'blank', before: 'God delivered the moral law on Mount Sinai in the',
            after: ' Commandments.', options: ['Ten', 'Seven', 'Three', 'Twelve'], answer: 'Ten',
            explain: '19.2 — delivered upon Mount Sinai in ten commandments.' },
          { type: 'mc', prompt: 'Into what kinds was God\u2019s law given to Israel distinguished?',
            options: ['Moral, ceremonial, and judicial', 'Old and new only', 'Written and spoken', 'Major and minor'],
            answer: 0, explain: '19.2\u201319.4 — the moral, the ceremonial, and the judicial laws.' },
        ] },
        { id: '19-2', title: 'Its use for believers', icon: 'compass', questions: [
          { type: 'truefalse', statement: 'The ceremonial laws, which pointed to Christ, are now abrogated.',
            answer: true, explain: '19.3 — the ceremonial laws are now abrogated under the New Testament.' },
          { type: 'mc', prompt: 'Are believers under the moral law as a covenant of works to be justified or condemned by it?',
            options: ['No — yet the moral law remains a rule of life for them', 'Yes, they are justified by keeping it', 'Yes, it condemns them still', 'It no longer applies to them at all'],
            answer: 0, explain: '19.6 — believers are not under the law as a covenant of works, yet it is of great use as a rule of life.' },
          { type: 'blank', before: 'The moral law forever binds all, both as to its matter and its',
            after: '.', options: ['authority', 'language', 'length', 'location'], answer: 'authority',
            explain: '19.5 — the moral law binds all, both as to matter and authority.' },
          { type: 'mc', prompt: 'What use is the moral law to a believer?',
            options: ['A rule of life showing God\u2019s will and driving them to Christ', 'A way to earn salvation', 'A burden now removed', 'Merely a historical record'],
            answer: 0, explain: '19.6\u201319.7 — it informs them of God\u2019s will and their duty, and shows their need of Christ.' },
        ] },
      ] },

    // ── Chapter 20 · Of the Gospel and the Extent of Grace ───────────────
    { id: 20, chapter: 20, title: 'Of the Gospel', short: 'The Gospel', theme: 'navy',
      blurb: 'The promise of Christ — and how the Spirit makes it effectual.',
      lessons: [
        { id: '20-1', title: 'The promise of Christ', icon: 'seal', questions: [
          { type: 'mc', prompt: 'When the covenant of works was broken, what did God give?',
            options: ['The promise of Christ, the seed of the woman', 'A harder law to keep', 'Nothing at all', 'A second covenant of works'],
            answer: 0, explain: '20.1 — it pleased God to give the promise of Christ, the seed of the woman.' },
          { type: 'truefalse', statement: 'The promise of salvation by Christ is revealed only by the Word of God.',
            answer: true, explain: '20.2 — this promise is revealed only by the Word of God.' },
          { type: 'blank', before: 'The revelation of the gospel to sinners is of the mere sovereign will and good',
            after: ' of God.', options: ['pleasure', 'fortune', 'memory', 'patience'], answer: 'pleasure',
            explain: '20.3 — of the mere sovereign will and good pleasure of God.' },
          { type: 'mc', prompt: 'Why must the gospel be revealed?',
            options: ['Salvation by Christ cannot be known by the light of nature, only by God\u2019s Word', 'Because people forget easily', 'Because nature contradicts it', 'It need not be revealed'],
            answer: 0, explain: '20.1\u201320.2 — the works of creation cannot make Christ known; he is revealed by the Word.' },
        ] },
        { id: '20-2', title: 'The Spirit makes it effectual', icon: 'flame', questions: [
          { type: 'truefalse', statement: 'Even those who hear the gospel cannot believe without the work of the Holy Spirit.',
            answer: true, explain: '20.4 — men cannot believe without an effectual, insuperable work of the Holy Spirit.' },
          { type: 'mc', prompt: 'What is needed for a sinner to believe and be converted?',
            options: ['The effectual, insuperable work of the Holy Spirit upon the soul', 'A persuasive enough sermon', 'A sincere personal effort', 'A favourable upbringing'],
            answer: 0, explain: '20.4 — an effectual, insuperable work of the Holy Spirit upon the whole soul.' },
          { type: 'blank', before: 'Without the effectual work of the Holy',
            after: ', no one can believe to salvation.', options: ['Spirit', 'Word', 'church', 'angel'], answer: 'Spirit',
            explain: '20.4 — the work of the Holy Spirit is necessary to produce a new spiritual life.' },
          { type: 'mc', prompt: 'What does the gospel reveal?',
            options: ['Christ and salvation by him', 'A code of ethics only', 'The history of Israel', 'The end of the world only'],
            answer: 0, explain: '20.1 — the gospel reveals Christ as the means of calling the elect.' },
        ] },
      ] },

    // ── Chapter 21 · Of Christian Liberty and Liberty of Conscience ──────
    { id: 21, chapter: 21, title: 'Of Christian Liberty', short: 'Liberty', theme: 'gold',
      blurb: 'The freedom Christ bought, and the conscience that answers to God alone.',
      lessons: [
        { id: '21-1', title: 'The liberty Christ bought', icon: 'star', questions: [
          { type: 'mc', prompt: 'What freedom did Christ purchase for believers?',
            options: ['Freedom from the guilt of sin, condemning wrath, and the curse of the law', 'Freedom to live however they please', 'Freedom from all duty to God', 'Freedom from every earthly trouble'],
            answer: 0, explain: '21.1 — freedom from the guilt of sin, the condemning wrath of God, and the curse of the law.' },
          { type: 'truefalse', statement: 'Christian liberty includes free access to God, serving him from love rather than slavish fear.',
            answer: true, explain: '21.1 — free access to God, yielding obedience not out of slavish fear but a child-like love.' },
          { type: 'blank', before: 'Believers are delivered from the guilt of sin and the',
            after: ' of the moral law.', options: ['curse', 'letter', 'gift', 'comfort'], answer: 'curse',
            explain: '21.1 — delivered from the condemning wrath of God and the curse of the moral law.' },
          { type: 'mc', prompt: 'From what are believers freed in Christian liberty?',
            options: ['This present evil world, bondage to Satan, the dominion of sin, and the sting of death', 'All physical suffering', 'The need to obey God', 'Membership in the church'],
            answer: 0, explain: '21.1 — from this present evil world, bondage to Satan, dominion of sin, and the sting of death.' },
        ] },
        { id: '21-2', title: 'Lord of the conscience', icon: 'shield', questions: [
          { type: 'truefalse', statement: 'God alone is Lord of the conscience.',
            answer: true, explain: '21.2 — God alone is Lord of the conscience.' },
          { type: 'mc', prompt: 'God has left the conscience free from —',
            options: ['Doctrines and commandments of men contrary to or beside his Word in faith and worship', 'All moral obligation', 'The teaching of Scripture', 'The voice of the Spirit'],
            answer: 0, explain: '21.2 — free from the doctrines and commandments of men which are contrary to, or beside, his Word.' },
          { type: 'mc', prompt: 'Those who use Christian liberty as a cloak for sin —',
            options: ['Destroy the very end of that liberty', 'Use it rightly', 'Are commended', 'Lose nothing by it'],
            answer: 0, explain: '21.3 — they who use liberty as an occasion to sin destroy the end of Christian liberty.' },
          { type: 'blank', before: 'God alone is Lord of the',
            after: '.', options: ['conscience', 'harvest', 'nations', 'angels'], answer: 'conscience',
            explain: '21.2 — God alone is Lord of the conscience.' },
        ] },
      ] },

    // ── Chapter 22 · Of Religious Worship and the Sabbath Day ────────────
    { id: 22, chapter: 22, title: 'Of Worship & the Sabbath', short: 'Worship', theme: 'navy',
      blurb: 'Worshiping God in his own appointed way, and the Lord\u2019s Day.',
      lessons: [
        { id: '22-1', title: 'Worship God\u2019s way', icon: 'flame', questions: [
          { type: 'mc', prompt: 'How is the true God to be worshiped?',
            options: ['Only in the way he himself has instituted in Scripture', 'However seems most moving to us', 'According to the customs of the age', 'In any sincere way at all'],
            answer: 0, explain: '22.1 — the acceptable way of worship is instituted by God and limited by his own revealed will.' },
          { type: 'truefalse', statement: 'We may worship God according to our own imaginations and inventions.',
            answer: false, explain: '22.1 — not according to the imaginations of men, nor any way not prescribed in Scripture.' },
          { type: 'blank', before: 'The acceptable way of worshiping the true God is',
            after: ' by himself.', options: ['instituted', 'invented', 'imagined', 'inherited'], answer: 'instituted',
            explain: '22.1 — the regulative principle: worship is instituted by God himself.' },
          { type: 'mc', prompt: 'To whom alone is religious worship to be given?',
            options: ['To God — Father, Son, and Holy Spirit — and to him alone', 'To God, angels, and saints', 'To God and his ministers', 'To whoever helps us most'],
            answer: 0, explain: '22.2 — worship is to be given to God, and to him alone; not to angels, saints, or any creature.' },
        ] },
        { id: '22-2', title: 'The Lord\u2019s Day', icon: 'sun', questions: [
          { type: 'truefalse', statement: 'God has appointed one day in seven for a Sabbath, to be kept holy to him.',
            answer: true, explain: '22.7 — God has particularly appointed one day in seven for a Sabbath.' },
          { type: 'mc', prompt: 'Since the resurrection of Christ, which day is the Christian Sabbath?',
            options: ['The first day of the week, the Lord\u2019s Day', 'The seventh day still', 'No fixed day', 'Whichever day is convenient'],
            answer: 0, explain: '22.7 — changed to the first day of the week, called the Lord\u2019s Day.' },
          { type: 'blank', before: 'Prayer is to be made in the name of the',
            after: ', by the help of the Spirit.', options: ['Son', 'church', 'saints', 'priest'], answer: 'Son',
            explain: '22.3 — prayer is to be made in the name of the Son, by the help of the Spirit, according to his will.' },
          { type: 'mc', prompt: 'How is the Lord\u2019s Day to be kept?',
            options: ['Holy to the Lord, in worship and rest from worldly employments', 'As an ordinary working day', 'For sport and recreation chiefly', 'However each person prefers'],
            answer: 0, explain: '22.8 — kept holy, resting from worldly employments and taken up in public and private worship.' },
        ] },
      ] },

    // ── Chapter 23 · Of Lawful Oaths and Vows ────────────────────────────
    { id: 23, chapter: 23, title: 'Of Lawful Oaths and Vows', short: 'Oaths & Vows', theme: 'gold',
      blurb: 'When calling God to witness is worship — and when it is sin.',
      lessons: [
        { id: '23-1', title: 'Lawful oaths', icon: 'seal', questions: [
          { type: 'mc', prompt: 'What is a lawful oath?',
            options: ['A part of religious worship, solemnly calling God to witness what one asserts or promises', 'A casual figure of speech', 'A magic formula', 'A relic of the old covenant only'],
            answer: 0, explain: '23.1 — a lawful oath is a part of religious worship, calling God to witness.' },
          { type: 'truefalse', statement: 'It is lawful to swear vain or rash oaths.',
            answer: false, explain: '23.x — vain and rash oaths are sinful and to be abhorred.' },
          { type: 'blank', before: 'Men ought to swear only by the',
            after: ' of God.', options: ['name', 'works', 'word', 'house'], answer: 'name',
            explain: '23.2 — the name of God only is that by which men ought to swear.' },
          { type: 'mc', prompt: 'In what is an oath to be taken?',
            options: ['In truth, righteousness, and judgment', 'In haste and heat', 'For convenience', 'For personal gain'],
            answer: 0, explain: '23.1 — swearing in truth, righteousness, and judgment.' },
        ] },
        { id: '23-2', title: 'Vows to God', icon: 'star', questions: [
          { type: 'truefalse', statement: 'A vow is of the nature of a promissory oath, and is to be made to God alone.',
            answer: true, explain: '23.5\u201323.6 — a vow is of the like nature with a promissory oath and ought to be made to God alone.' },
          { type: 'mc', prompt: 'To whom is a vow to be made?',
            options: ['To God alone', 'To any saint', 'To the church', 'To one\u2019s elders'],
            answer: 0, explain: '23.6 — a vow is to be made to God alone.' },
          { type: 'blank', before: 'An oath is to be taken in truth, righteousness, and',
            after: '.', options: ['judgment', 'anger', 'secret', 'haste'], answer: 'judgment',
            explain: '23.1 — in truth, righteousness, and judgment.' },
          { type: 'mc', prompt: 'An oath rashly broken or falsely sworn is —',
            options: ['Sinful, and to be repented of', 'Of no account', 'A minor matter', 'Acceptable if well meant'],
            answer: 0, explain: 'Swearing falsely or vainly is sin against the third commandment.' },
        ] },
      ] },
  ];

  window.CH_MORE = (window.CH_MORE || []).concat(units);
})();
