/* Cornerstone — chapters 24–32, drawn from the 1689 LBCF (modern English).
   Pushed onto window.CH_MORE (loaded before data.js). */
(function () {
  const units = [
    // ── Chapter 24 · Of the Civil Magistrate ─────────────────────────────
    { id: 24, chapter: 24, title: 'Of the Civil Magistrate', short: 'The Magistrate', theme: 'navy',
      blurb: 'God\u2019s ordinance of government, and the Christian\u2019s duty within it.',
      lessons: [
        { id: '24-1', title: 'Ordained by God', icon: 'shield', questions: [
          { type: 'mc', prompt: 'Who has ordained civil magistrates to be over the people?',
            options: ['God, the supreme Lord and King of all the world', 'The people, by their own will alone', 'The church', 'No one \u2014 they arose by chance'],
            answer: 0, explain: '24.1 — God, the supreme Lord and King of all the world, has ordained civil magistrates under him.' },
          { type: 'truefalse', statement: 'Magistrates are armed with the power of the sword for the defence of the good and the punishment of evildoers.',
            answer: true, explain: '24.1 — armed with the power of the sword, for defence and encouragement of good, and punishment of evil.' },
          { type: 'blank', before: 'God has ordained civil magistrates for his own glory and the public',
            after: '.', options: ['good', 'wealth', 'fame', 'peace'], answer: 'good',
            explain: '24.1 — for his own glory and the public good.' },
          { type: 'mc', prompt: 'For what end are magistrates ordained?',
            options: ['For God\u2019s glory and the public good', 'For the ruler\u2019s personal gain', 'To govern the church', 'For no settled purpose'],
            answer: 0, explain: '24.1 — under God, over the people, for his glory and the public good.' },
        ] },
        { id: '24-2', title: 'The Christian and the state', icon: 'seal', questions: [
          { type: 'truefalse', statement: 'It is lawful for Christians to accept and execute the office of a magistrate.',
            answer: true, explain: '24.2 — it is lawful for Christians to accept and execute the office of a magistrate.' },
          { type: 'mc', prompt: 'What is the people\u2019s duty toward their magistrates?',
            options: ['To pray for them, honour them, pay taxes, and obey their lawful commands', 'To ignore them entirely', 'To obey only when convenient', 'To rule over them'],
            answer: 0, explain: '24.3 — to pray for magistrates, honour their persons, pay tribute, and obey lawful commands.' },
          { type: 'blank', before: 'Believers are to be subject to the magistrate\u2019s authority for',
            after: '\u2019 sake.', options: ['conscience', 'profit', 'comfort', 'fashion'], answer: 'conscience',
            explain: '24.3 — to be subject to their authority, for conscience\u2019 sake.' },
          { type: 'mc', prompt: 'For whose sake are believers to be subject to lawful authority?',
            options: ['For conscience\u2019 sake', 'For fear of punishment only', 'For social standing', 'For no reason given'],
            answer: 0, explain: '24.3 — subject for conscience\u2019 sake (Romans 13:5).' },
        ] },
      ] },

    // ── Chapter 25 · Of Marriage ─────────────────────────────────────────
    { id: 25, chapter: 25, title: 'Of Marriage', short: 'Marriage', theme: 'gold',
      blurb: 'The covenant of one man and one woman, and its God-given ends.',
      lessons: [
        { id: '25-1', title: 'One man, one woman', icon: 'sun', questions: [
          { type: 'mc', prompt: 'Marriage is to be between —',
            options: ['One man and one woman', 'Any two consenting people', 'Several wives and one husband', 'Whatever a society allows'],
            answer: 0, explain: '25.1 — marriage is to be between one man and one woman.' },
          { type: 'truefalse', statement: 'It is lawful for a man to have more than one wife at the same time.',
            answer: false, explain: '25.1 — it is not lawful for any man to have more than one wife at the same time.' },
          { type: 'blank', before: 'Marriage was ordained for the mutual help of husband and',
            after: '.', options: ['wife', 'state', 'church', 'kin'], answer: 'wife',
            explain: '25.2 — ordained for the mutual help of husband and wife.' },
          { type: 'mc', prompt: 'For what ends was marriage ordained?',
            options: ['Mutual help, the increase of mankind, and the prevention of uncleanness', 'Property and inheritance only', 'Political alliance', 'Convenience alone'],
            answer: 0, explain: '25.2 — for mutual help, the increase of mankind with legitimate issue, and preventing uncleanness.' },
        ] },
        { id: '25-2', title: 'Marry in the Lord', icon: 'star', questions: [
          { type: 'truefalse', statement: 'It is the duty of Christians to marry only in the Lord.',
            answer: true, explain: '25.3 — it is the duty of Christians to marry only in the Lord.' },
          { type: 'mc', prompt: 'Whom should those who profess the true religion not marry?',
            options: ['Infidels or idolaters', 'Anyone of another town', 'People who are poor', 'Those of another trade'],
            answer: 0, explain: '25.3 — they should not marry with infidels or idolaters.' },
          { type: 'mc', prompt: 'Marriage ought not to be within the degrees of —',
            options: ['Consanguinity or affinity forbidden in the Word', 'Different nations', 'Different ages', 'Different income'],
            answer: 0, explain: '25.4 — not within the degrees of consanguinity or affinity forbidden in the Word.' },
          { type: 'blank', before: 'It is lawful for all sorts of people to marry who are able to give their',
            after: '.', options: ['consent', 'dowry', 'land', 'oath'], answer: 'consent',
            explain: '25.3 — lawful for all who are able with judgment to give their consent.' },
        ] },
      ] },

    // ── Chapter 26 · Of the Church ───────────────────────────────────────
    { id: 26, chapter: 26, title: 'Of the Church', short: 'The Church', theme: 'navy',
      blurb: 'Christ\u2019s body \u2014 universal and gathered \u2014 with Christ as its only head.',
      lessons: [
        { id: '26-1', title: 'The universal church', icon: 'crown', questions: [
          { type: 'mc', prompt: 'The catholic (universal) church, which is invisible, consists of —',
            options: ['The whole number of the elect, gathered under Christ the head', 'One denomination only', 'All people everywhere', 'The clergy alone'],
            answer: 0, explain: '26.1 — it consists of the whole number of the elect, gathered into one under Christ.' },
          { type: 'truefalse', statement: 'The Lord Jesus Christ is the head of the church.',
            answer: true, explain: '26.4 — the Lord Jesus Christ is the head of the church.' },
          { type: 'blank', before: 'The only head of the church is the Lord Jesus',
            after: '.', options: ['Christ', 'Peter', 'Paul', 'Pope'], answer: 'Christ',
            explain: '26.4 — Christ alone is head; the Pope cannot be head of the church.' },
          { type: 'mc', prompt: 'Who is the only head of the church?',
            options: ['The Lord Jesus Christ alone', 'The Pope of Rome', 'A council of elders', 'The civil magistrate'],
            answer: 0, explain: '26.4 — Christ alone; the Confession denies the Pope can be its head.' },
        ] },
        { id: '26-2', title: 'Visible churches', icon: 'seal', questions: [
          { type: 'truefalse', statement: 'The purest churches under heaven are subject to mixture and error.',
            answer: true, explain: '26.3 — the purest churches are subject to mixture and error.' },
          { type: 'mc', prompt: 'Will Christ ever be left without a church in the world?',
            options: ['No \u2014 he always has had, and ever shall have, a kingdom of believers', 'Yes, at times the church vanishes', 'Only in the last days', 'The Confession does not say'],
            answer: 0, explain: '26.3 — Christ always has had, and shall have, a kingdom in this world to the end.' },
          { type: 'mc', prompt: 'What officers did Christ appoint for his churches?',
            options: ['Elders (bishops) and deacons', 'Priests and cardinals', 'Kings and judges', 'No officers at all'],
            answer: 0, explain: '26.8 — the officers appointed by Christ are elders (bishops) and deacons.' },
          { type: 'blank', before: 'Those throughout the world professing the faith of the gospel may be called visible',
            after: '.', options: ['saints', 'kings', 'priests', 'judges'], answer: 'saints',
            explain: '26.2 — such professing persons may be called visible saints.' },
        ] },
      ] },

    // ── Chapter 27 · Of the Communion of Saints ──────────────────────────
    { id: 27, chapter: 27, title: 'Of the Communion of Saints', short: 'Communion', theme: 'gold',
      blurb: 'United to Christ, the saints share life with him and with each other.',
      lessons: [
        { id: '27-1', title: 'Union and communion', icon: 'star', questions: [
          { type: 'mc', prompt: 'Saints united to Christ have fellowship with him in —',
            options: ['His graces, sufferings, death, resurrection, and glory', 'His divine essence', 'His office as mediator', 'His eternal decree'],
            answer: 0, explain: '27.1 — they have fellowship in his graces, sufferings, death, resurrection, and glory.' },
          { type: 'truefalse', statement: 'All saints are united to Jesus Christ their head by his Spirit and by faith.',
            answer: true, explain: '27.1 — united to Christ their head by his Spirit and by faith.' },
          { type: 'blank', before: 'Saints are united to Christ their head by his Spirit and by',
            after: '.', options: ['faith', 'works', 'birth', 'oath'], answer: 'faith',
            explain: '27.1 — by his Spirit, and by faith.' },
          { type: 'mc', prompt: 'What are saints by profession bound to maintain?',
            options: ['A holy fellowship in worship and mutual edification', 'A private, solitary faith', 'Strict separation from one another', 'Communion only with leaders'],
            answer: 0, explain: '27.2 — bound to maintain a holy fellowship and communion in worship and mutual edification.' },
        ] },
        { id: '27-2', title: 'Helping one another', icon: 'sun', questions: [
          { type: 'truefalse', statement: 'The communion of saints includes relieving one another in outward things, as ability allows.',
            answer: true, explain: '27.2 — relieving each other in outward things, according to their abilities and necessities.' },
          { type: 'mc', prompt: 'How is the communion of saints expressed?',
            options: ['In worship, spiritual edification, and relieving each other\u2019s needs', 'In sharing all property by force', 'In agreeing on every opinion', 'In withdrawing from the world entirely'],
            answer: 0, explain: '27.2 — in worship, mutual edification, and relief of one another\u2019s outward needs.' },
          { type: 'blank', before: 'Saints have fellowship with Christ in his graces, sufferings, death, resurrection, and',
            after: '.', options: ['glory', 'fame', 'wealth', 'rest'], answer: 'glory',
            explain: '27.1 — fellowship in his glory.' },
          { type: 'type', prompt: 'The saints are united to their head, Jesus ________.',
            accept: ['christ'], answer: 'Christ', explain: '27.1 — united to Christ their head.' },
        ] },
      ] },

    // ── Chapter 28 · Of Baptism and the Lord's Supper ────────────────────
    { id: 28, chapter: 28, title: 'Of Baptism & the Lord\u2019s Supper', short: 'The Ordinances', theme: 'navy',
      blurb: 'Two ordinances given by Christ, to be kept until he comes.',
      lessons: [
        { id: '28-1', title: 'Two ordinances of Christ', icon: 'seal', questions: [
          { type: 'mc', prompt: 'Who instituted baptism and the Lord\u2019s Supper?',
            options: ['The Lord Jesus Christ, the only lawgiver', 'The apostles, on their own authority', 'The early church councils', 'Moses'],
            answer: 0, explain: '28.1 — appointed by the Lord Jesus, the only lawgiver.' },
          { type: 'truefalse', statement: 'Baptism and the Lord\u2019s Supper are to be continued in the church to the end of the world.',
            answer: true, explain: '28.1 — to be continued in his church to the end of the world.' },
          { type: 'blank', before: 'Baptism and the Lord\u2019s Supper are ordinances of positive and sovereign',
            after: '.', options: ['institution', 'tradition', 'opinion', 'invention'], answer: 'institution',
            explain: '28.1 — ordinances of positive and sovereign institution.' },
          { type: 'mc', prompt: 'By whom are these ordinances to be administered?',
            options: ['Only by those qualified and called, according to Christ\u2019s commission', 'By any believer at any time', 'By civil officers', 'By the recipients themselves'],
            answer: 0, explain: '28.2 — to be administered by those only who are qualified and called, per Christ\u2019s commission.' },
        ] },
        { id: '28-2', title: 'Appointed by Christ alone', icon: 'shield', questions: [
          { type: 'truefalse', statement: 'Only those rightly qualified and called by Christ may administer the ordinances.',
            answer: true, explain: '28.2 — to be administered only by those qualified and thereunto called.' },
          { type: 'mc', prompt: 'These holy appointments were given by —',
            options: ['The Lord Jesus, the only lawgiver of his church', 'The free choice of each congregation', 'Ancient custom', 'The state'],
            answer: 0, explain: '28.1 — the Lord Jesus, the only lawgiver.' },
          { type: 'blank', before: 'These ordinances are to be continued in the church to the end of the',
            after: '.', options: ['world', 'age', 'year', 'feast'], answer: 'world',
            explain: '28.1 — to the end of the world.' },
        ] },
      ] },

    // ── Chapter 29 · Of Baptism ──────────────────────────────────────────
    { id: 29, chapter: 29, title: 'Of Baptism', short: 'Baptism', theme: 'gold',
      blurb: 'A sign of union with Christ \u2014 for those who profess faith.',
      lessons: [
        { id: '29-1', title: 'A sign of union with Christ', icon: 'star', questions: [
          { type: 'mc', prompt: 'Baptism is a sign to the baptized of —',
            options: ['Fellowship with Christ in his death and resurrection, and of newness of life', 'Membership in a nation', 'The forgiveness earned by the act itself', 'A social ceremony only'],
            answer: 0, explain: '29.1 — a sign of fellowship with Christ in his death and resurrection, and walking in newness of life.' },
          { type: 'truefalse', statement: 'Baptism signifies being engrafted into Christ and the remission of sins.',
            answer: true, explain: '29.1 — a sign of being engrafted into him, and of remission of sins.' },
          { type: 'blank', before: 'Baptism is a sign of the believer\u2019s fellowship with Christ in his death and',
            after: '.', options: ['resurrection', 'ascension', 'temptation', 'teaching'], answer: 'resurrection',
            explain: '29.1 — fellowship with Christ in his death and resurrection.' },
          { type: 'mc', prompt: 'What is the outward element used in baptism?',
            options: ['Water', 'Oil', 'Wine', 'Ash'],
            answer: 0, explain: '29.3 — the outward element is water.' },
        ] },
        { id: '29-2', title: 'Who, and how', icon: 'seal', questions: [
          { type: 'mc', prompt: 'Who are the proper subjects of baptism?',
            options: ['Those who actually profess repentance and faith in Christ', 'All infants of the nation', 'Anyone who requests it', 'Only the children of ministers'],
            answer: 0, explain: '29.2 — those who profess repentance toward God and faith in Christ are the only proper subjects.' },
          { type: 'truefalse', statement: 'Infants who cannot yet profess faith are the proper subjects of baptism.',
            answer: false, explain: '29.2 — believers\u2019 baptism: only those who profess faith and repentance are proper subjects.' },
          { type: 'mc', prompt: 'What manner of baptism does the Confession require?',
            options: ['Immersion \u2014 dipping the person in water', 'Sprinkling a few drops', 'Pouring on the head', 'Any of these equally'],
            answer: 0, explain: '29.4 — immersion, or dipping of the person in water, is necessary to its due administration.' },
          { type: 'blank', before: 'The person is baptized in the name of the Father, the Son, and the Holy',
            after: '.', options: ['Spirit', 'Church', 'Word', 'Name'], answer: 'Spirit',
            explain: '29.3 — baptized in the name of the Father, and of the Son, and of the Holy Spirit.' },
        ] },
      ] },

    // ── Chapter 30 · Of the Lord's Supper ────────────────────────────────
    { id: 30, chapter: 30, title: 'Of the Lord\u2019s Supper', short: 'The Supper', theme: 'navy',
      blurb: 'A remembrance of Christ\u2019s one sacrifice, received by faith.',
      lessons: [
        { id: '30-1', title: 'A perpetual remembrance', icon: 'flame', questions: [
          { type: 'mc', prompt: 'For what was the Lord\u2019s Supper instituted?',
            options: ['The perpetual remembrance and showing forth of Christ\u2019s sacrifice in his death', 'A repeated sacrifice for sins', 'An ordinary meal', 'A feast for the clergy only'],
            answer: 0, explain: '30.1 — for the perpetual remembrance and showing forth the sacrifice of himself in his death.' },
          { type: 'truefalse', statement: 'In the Lord\u2019s Supper, Christ is offered up afresh as a real sacrifice for sin.',
            answer: false, explain: '30.2 — Christ is not offered up; it is a memorial of that one offering once for all.' },
          { type: 'blank', before: 'The Supper is for the perpetual',
            after: ' of the sacrifice of Christ.', options: ['remembrance', 'repetition', 'replacement', 'reward'], answer: 'remembrance',
            explain: '30.1 — for the perpetual remembrance of Christ\u2019s death.' },
          { type: 'mc', prompt: 'What does the Supper provide for believers?',
            options: ['Confirmation of their faith and spiritual nourishment and growth in Christ', 'Forgiveness earned by eating', 'A guarantee of earthly blessing', 'Nothing in particular'],
            answer: 0, explain: '30.1 — the confirmation of faith, and spiritual nourishment and growth in Christ.' },
        ] },
        { id: '30-2', title: 'Christ received by faith', icon: 'seal', questions: [
          { type: 'truefalse', statement: 'The doctrine of transubstantiation is repugnant to Scripture.',
            answer: true, explain: '30.6 — transubstantiation is repugnant not only to Scripture but to common sense and reason.' },
          { type: 'mc', prompt: 'How do worthy receivers feed on Christ in the Supper?',
            options: ['Inwardly by faith, really feeding on Christ crucified, spiritually present', 'By literally eating his physical body', 'By the act of eating alone', 'They do not feed on him at all'],
            answer: 0, explain: '30.7 — worthy receivers inwardly by faith really receive and feed upon Christ crucified.' },
          { type: 'mc', prompt: 'Are the bread and wine changed into the actual body and blood of Christ?',
            options: ['No \u2014 the elements remain truly bread and wine', 'Yes, they become his literal flesh', 'Only the bread is changed', 'The Confession leaves it open'],
            answer: 0, explain: '30.6 — the elements remain truly bread and wine, as before.' },
          { type: 'blank', before: 'Worthy receivers spiritually feed upon Christ by',
            after: '.', options: ['faith', 'sight', 'merit', 'works'], answer: 'faith',
            explain: '30.7 — they spiritually receive and feed upon Christ by faith.' },
        ] },
      ] },

    // ── Chapter 31 · Of the State of Man after Death & the Resurrection ──
    { id: 31, chapter: 31, title: 'Of Death & the Resurrection', short: 'Resurrection', theme: 'gold',
      blurb: 'What becomes of body and soul in death \u2014 and at the last day.',
      lessons: [
        { id: '31-1', title: 'After death', icon: 'sun', questions: [
          { type: 'mc', prompt: 'After death, what happens to the bodies of men?',
            options: ['They return to dust and see corruption', 'They sleep with the soul until judgment', 'They are immediately glorified', 'They cease to exist forever'],
            answer: 0, explain: '31.1 — the bodies of men after death return to dust, and see corruption.' },
          { type: 'truefalse', statement: 'The souls of men neither die nor sleep, but return immediately to God who gave them.',
            answer: true, explain: '31.1 — their souls, which neither die nor sleep, return immediately to God.' },
          { type: 'blank', before: 'The souls of the righteous are received into',
            after: '.', options: ['paradise', 'silence', 'sleep', 'dust'], answer: 'paradise',
            explain: '31.1 — the souls of the righteous are received into paradise, with Christ.' },
          { type: 'mc', prompt: 'Where do the souls of the wicked go at death?',
            options: ['Cast into hell, reserved for the judgment of the great day', 'Into a second chance', 'Into nothingness', 'Into paradise with the rest'],
            answer: 0, explain: '31.1 — the souls of the wicked are cast into hell, reserved to the judgment of the great day.' },
        ] },
        { id: '31-2', title: 'The resurrection', icon: 'star', questions: [
          { type: 'truefalse', statement: 'At the last day, all the dead shall be raised up with the selfsame bodies.',
            answer: true, explain: '31.2 — all the dead shall be raised up with the selfsame bodies, and none other.' },
          { type: 'mc', prompt: 'Those found alive at the last day shall —',
            options: ['Not die, but be changed', 'Die first, then rise', 'Remain unchanged', 'Be passed over'],
            answer: 0, explain: '31.2 — those found alive shall not die, but be changed.' },
          { type: 'blank', before: 'The unjust shall be raised to dishonour; the just unto',
            after: '.', options: ['honour', 'sleep', 'dust', 'silence'], answer: 'honour',
            explain: '31.3 — the bodies of the unjust raised to dishonour; of the just, unto honour.' },
          { type: 'type', prompt: 'At the last day, all the dead shall be ________.',
            accept: ['raised', 'resurrected', 'raised up'], answer: 'raised',
            explain: '31.2 — all the dead shall be raised up.' },
        ] },
      ] },

    // ── Chapter 32 · Of the Last Judgment ────────────────────────────────
    { id: 32, chapter: 32, title: 'Of the Last Judgment', short: 'Last Judgment', theme: 'navy',
      blurb: 'The appointed day when Christ will judge the world in righteousness.',
      lessons: [
        { id: '32-1', title: 'The appointed day', icon: 'crown', questions: [
          { type: 'mc', prompt: 'By whom will God judge the world in righteousness?',
            options: ['By Jesus Christ', 'By the angels', 'By the apostles', 'By each person\u2019s conscience alone'],
            answer: 0, explain: '32.1 — God has appointed a day to judge the world in righteousness by Jesus Christ.' },
          { type: 'truefalse', statement: 'God has appointed a day in which he will judge the world in righteousness.',
            answer: true, explain: '32.1 — God has appointed a day wherein he will judge the world in righteousness.' },
          { type: 'blank', before: 'All power and judgment is given to Jesus',
            after: ' by the Father.', options: ['Christ', 'Peter', 'Paul', 'Michael'], answer: 'Christ',
            explain: '32.1 — all power and judgment is given to Christ by the Father.' },
          { type: 'mc', prompt: 'Who shall appear before the judgment seat?',
            options: ['All persons that have ever lived, to give account', 'Only the wicked', 'Only the church', 'Only those alive at the time'],
            answer: 0, explain: '32.1 — all persons that have lived shall appear to give an account.' },
        ] },
        { id: '32-2', title: 'Why, and when', icon: 'sun', questions: [
          { type: 'mc', prompt: 'What is the end (purpose) of God\u2019s appointing this day?',
            options: ['The manifestation of the glory of his mercy and of his justice', 'To frighten the world only', 'To reward the powerful', 'It has no stated purpose'],
            answer: 0, explain: '32.2 — for the manifestation of the glory of his mercy in the elect, and his justice in the reprobate.' },
          { type: 'truefalse', statement: 'God has left the day of judgment unknown to men, that they may be watchful.',
            answer: true, explain: '32.3 — he will have that day unknown to men, that they may shake off security and be watchful.' },
          { type: 'blank', before: 'The day of judgment is kept unknown so that men may shake off all',
            after: ' security.', options: ['carnal', 'civil', 'public', 'eternal'], answer: 'carnal',
            explain: '32.3 — that they may shake off all carnal security.' },
          { type: 'mc', prompt: 'The certainty of a coming judgment is meant to —',
            options: ['Deter men from sin and comfort the godly', 'Make believers anxious', 'Excuse present sin', 'Discourage all effort'],
            answer: 0, explain: '32.3 — to deter all men from sin, and for the greater consolation of the godly.' },
        ] },
      ] },
  ];

  window.CH_MORE = (window.CH_MORE || []).concat(units);
})();
