/* Cornerstone — Reading text, chapters 1–8 (1689 LBCF, modern English rendering).
   window.READING[chapter] = [paragraph, paragraph, ...] */
(function () {
  const R = (window.READING = window.READING || {});

  R[1] = [
    "The Bible is the only sufficient, certain, and infallible standard of all saving knowledge, faith, and obedience.^ The light of nature and the works of creation and providence clearly demonstrate the goodness, wisdom, and power of God, so that people have no excuse. However, these things are not sufficient to give the knowledge of God and his will that is necessary for salvation.^ Therefore, the Lord was pleased at various times and in various manners to reveal himself and to declare his will to his church.^ Then, to better preserve and propagate the truth, and to better establish and comfort the church against the corruption of the flesh and the malice of Satan and the world, God put his revelations completely into writing. Now, the Bible is necessary because God's former ways of revealing his will to his people have ceased.^",
    "The Bible, or the written Word of God, contains the Old and New Testaments, which are these:\nTHE OLD TESTAMENT\nGenesis, Exodus, Leviticus, Numbers, Deuteronomy, Joshua, Judges, Ruth, 1 Samuel, 2 Samuel, 1 Kings, 2 Kings, 1 Chronicles, 2 Chronicles, Ezra, Nehemiah, Esther, Job, Psalms, Proverbs, Ecclesiastes, The Song of Solomon, Isaiah, Jeremiah, Lamentations, Ezekiel, Daniel, Hosea, Joel, Amos, Obadiah, Jonah, Micah, Nahum, Habakkuk, Zephaniah, Haggai, Zechariah, Malachi.\nTHE NEW TESTAMENT\nMatthew, Mark, Luke, John, Acts, Romans, 1 Corinthians, 2 Corinthians, Galatians, Ephesians, Philippians, Colossians, 1 Thessalonians, 2 Thessalonians, 1 Timothy, 2 Timothy, Titus, Philemon, Hebrews, James, 1 Peter, 2 Peter, 1 John, 2 John, 3 John, Jude, Revelation.\nThese are all given by the inspiration of God to be the standard of faith and life.^",
    "The books commonly called the Apocrypha were not given by divine inspiration, and so are no part of the canon of the Bible. They therefore have no authority for the church of God, and are not to be approved or used in any way different from other human writings.^",
    "The authority of the Bible, for which it ought to be believed, does not depend on the testimony of any person or church, but completely on God, its author, who is truth itself. The Bible is therefore to be received because it is the Word of God.^",
    "The testimony of the church of God may move and persuade us to a high and reverent esteem of the Bible. The heavenliness of its contents, the power of its teachings, the majesty of its style, the agreement of all its parts, its overall aim (to give all glory to God), the full disclosure it makes of the only way of salvation, and many other incomparable excellencies and complete perfections, are arguments by which it abundantly proves itself to be the Word of God. Even so, our full persuasion and assurance of its infallible truth and divine authority comes from the inward work of the Holy Spirit, who bears witness by and with the Word in our hearts.^",
    "The whole counsel of God concerning everything necessary for his own glory and for our salvation, faith, and life is either explicitly stated in the Bible or may be deduced from it by good and necessary inference. Nothing is ever to be added to it, whether by new revelations of the Spirit or by the traditions of men.^ Nevertheless, we acknowledge that the inward illumination of the Spirit of God is necessary for a saving understanding of the things revealed in the Word; and that there are some circumstances concerning the worship of God and the government of the church, common to human actions and societies, which are to be ordered by the light of nature and Christian prudence, according to the general rules of the Word, which are always to be observed.^",
    "Not everything in the Bible is equally plain in itself, nor equally clear to everyone. Yet the things that must be known, believed, and observed for salvation are so clearly stated and explained in one place or another that not only the educated but also the uneducated may gain a sufficient understanding of them through a proper use of the ordinary means.^",
    "The Old Testament in Hebrew and the New Testament in Greek were directly inspired by God and have been kept pure throughout the ages by his singular care and providence. They are therefore authentic, so that in all controversies of religion the church is to make its final appeal to them.^ But because these original languages are not known to all the people of God — who have a right to the Scriptures, and an interest in them, and are commanded to read and search them in the fear of God — the Bible is to be translated into the common language of every nation to which it comes, so that the Word of God may dwell richly in everyone, and they may worship him in an acceptable manner, and through patience and the comfort of the Scriptures may have hope.^",
    "The infallible rule for interpreting the Bible is the Bible itself. So when there is a question about the true and full meaning of any passage (which is not many, but one), it must be searched out and understood by other passages that speak more clearly.^",
    "The supreme judge by which all controversies of religion are to be settled, and all decrees of councils, opinions of ancient writers, teachings of men, and private spirits are to be examined, and in whose judgment we are to rest, can be nothing other than the Bible delivered by the Spirit. In this Bible our faith is finally resolved.^",
  ];

  R[2] = [
    "The Lord our God is but one only living and true God; whose subsistence is in and of himself, infinite in being and perfection. His essence cannot be comprehended by anyone but himself. He is a most pure spirit, invisible, without body, parts, or passions; he alone has immortality, dwelling in the light which no one can approach. He is immutable, immense, eternal, incomprehensible, almighty, in every way infinite, most holy, most wise, most free, most absolute; working all things according to the counsel of his own unchangeable and most righteous will, for his own glory. He is most loving, gracious, merciful, long-suffering, abundant in goodness and truth, forgiving iniquity, transgression, and sin; the rewarder of those who diligently seek him; and also most just and terrible in his judgments, hating all sin, and one who will by no means clear the guilty.",
    "God has all life, glory, goodness, and blessedness in and of himself; he alone is all-sufficient in himself, not standing in need of any creature he has made, nor deriving any glory from them, but only manifesting his own glory in, by, to, and upon them. He is the only fountain of all being, from whom, through whom, and to whom are all things. He has most sovereign dominion over all creatures, to do by them, for them, or upon them whatever he pleases. In his sight all things are open and manifest; his knowledge is infinite, infallible, and not dependent upon the creature, so that to him nothing is contingent or uncertain. He is most holy in all his counsels, in all his works, and in all his commands. To him is due from angels and men whatever worship, service, or obedience they owe as creatures to the Creator.",
    "In this divine and infinite Being there are three subsistences: the Father, the Word (or Son), and the Holy Spirit; of one substance, power, and eternity, each having the whole divine essence, yet this essence undivided. The Father is of none, neither begotten nor proceeding; the Son is eternally begotten of the Father; the Holy Spirit proceeds from the Father and the Son. All three are infinite, without beginning, and therefore but one God, who is not to be divided in nature and being, but distinguished by several peculiar relative properties and personal relations. This doctrine of the Trinity is the foundation of all our communion with God, and of our comfortable dependence on him.",
  ];

  R[3] = [
    "God has decreed in himself, from all eternity, by the most wise and holy counsel of his own will, freely and unchangeably, all things whatsoever come to pass. Yet he is not the author of sin, nor does he have fellowship with any in their sin; nor is violence offered to the will of the creature, nor is the liberty or contingency of second causes taken away, but rather established. In this God's wisdom is displayed in disposing all things, and his power and faithfulness in accomplishing his decree.",
    "Although God knows whatever may or can come to pass upon all supposed conditions, yet he has not decreed anything because he foresaw it as future, or as that which would come to pass upon such conditions.",
    "By the decree of God, for the manifestation of his glory, some men and angels are predestined (or foreordained) to eternal life through Jesus Christ, to the praise of his glorious grace; others are left to act in their sin to their just condemnation, to the praise of his glorious justice.",
    "These angels and men, thus predestined and foreordained, are particularly and unchangeably designed, and their number is so certain and definite that it cannot be either increased or diminished.",
    "Those of mankind who are predestined to life, God chose in Christ before the foundation of the world, according to his eternal and immutable purpose and the secret counsel and good pleasure of his will — out of his mere free grace and love, without any foresight of faith or good works, or perseverance in either, or anything else in the creature, as conditions or causes moving him to it; and all to the praise of his glorious grace.",
    "As God has appointed the elect to glory, so he has, by the eternal and most free purpose of his will, foreordained all the means to it. Therefore those who are elected, being fallen in Adam, are redeemed by Christ, effectually called to faith in Christ by his Spirit working in due season, justified, adopted, sanctified, and kept by his power through faith to salvation. None but the elect alone are redeemed by Christ, and effectually called, justified, adopted, sanctified, and saved.",
    "The doctrine of this high mystery of predestination is to be handled with special prudence and care, so that men, attending to the will of God revealed in his Word and yielding obedience to it, may, from the certainty of their effectual vocation, be assured of their eternal election. So this doctrine affords matter of praise, reverence, and admiration of God, and of humility, diligence, and abundant consolation to all who sincerely obey the gospel.",
  ];

  R[4] = [
    "In the beginning it pleased God the Father, Son, and Holy Spirit, for the manifestation of the glory of his eternal power, wisdom, and goodness, to create the world and all things in it, whether visible or invisible, in the space of six days; and all very good.",
    "After God had made all other creatures, he created man, male and female, with reasonable and immortal souls, fitting them for that life lived to God for which they were created. They were made after the image of God, in knowledge, righteousness, and true holiness, having the law of God written in their hearts and the power to fulfill it; and yet they were under the possibility of transgressing, being left to the liberty of their own will, which was subject to change.",
    "Besides the law written in their hearts, they received a command not to eat of the tree of the knowledge of good and evil; and while they kept this command, they were happy in their fellowship with God, and had dominion over the creatures.",
  ];

  R[5] = [
    "God the good Creator of all things, in his infinite power and wisdom, upholds, directs, disposes, and governs all creatures and things, from the greatest even to the least, by his most wise and holy providence, to the end for which they were created — according to his infallible foreknowledge and the free and immutable counsel of his own will, to the praise of the glory of his wisdom, power, justice, infinite goodness, and mercy.",
    "Although, in relation to the foreknowledge and decree of God, the first cause, all things come to pass immutably and infallibly; yet by the same providence he orders them to fall out according to the nature of second causes, either necessarily, freely, or contingently.",
    "God, in his ordinary providence, makes use of means; yet he is free to work without, above, and against them at his pleasure.",
    "The almighty power, unsearchable wisdom, and infinite goodness of God so far manifest themselves in his providence that it extends itself even to the first fall and all other sins of angels and men — and that not by a bare permission, but a permission joined with a most wise and powerful bounding, and otherwise ordering and governing them, in a manifold dispensation, to his own holy ends. Yet so that the sinfulness of their acts proceeds only from the creatures, and not from God, who, being most holy and righteous, is neither the author nor approver of sin.",
    "The most wise, righteous, and gracious God often leaves for a season his own children to manifold temptations and the corruption of their own hearts, to chastise them for their former sins, or to reveal to them the hidden strength of corruption and the deceitfulness of their hearts, that they may be humbled; and to raise them to a closer and more constant dependence for their support upon himself, and to make them more watchful against all future occasions of sin, and for various other just and holy ends. So whatever befalls any of his elect is by his appointment, for his glory, and their good.",
    "As for those wicked and ungodly men whom God, as a righteous judge, blinds and hardens for their former sins, he not only withholds his grace, by which they might have been enlightened in their understandings and worked upon in their hearts, but sometimes also withdraws the gifts they had, and exposes them to such objects as their corruption makes occasions of sin; and gives them over to their own lusts, the temptations of the world, and the power of Satan, so that they harden themselves under the very means God uses for the softening of others.",
    "As the providence of God reaches in general to all creatures, so in a most special manner it takes care of his church, and disposes all things to its good.",
  ];

  R[6] = [
    "Although God created man upright and perfect, and gave him a righteous law that would have been for life had he kept it and threatened death upon breaking it, yet he did not long abide in this honor. Satan used the subtlety of the serpent to subdue Eve, who then seduced Adam; and he, without any compulsion, willfully transgressed the law under which they were created, and the command given to them, by eating the forbidden fruit. It pleased God, according to his wise and holy counsel, to permit this, having purposed to order it to his own glory.",
    "By this sin our first parents fell from their original righteousness and communion with God, and we in them; whereby death came upon all, all becoming dead in sin and wholly defiled in all the faculties and parts of soul and body.",
    "Since they were the root, and by God's appointment standing in the place of all mankind, the guilt of this sin was imputed, and the corrupted nature conveyed, to all their posterity descending from them by ordinary generation — being now conceived in sin, and by nature children of wrath, the servants of sin, the subjects of death and all other miseries (spiritual, temporal, and eternal) unless the Lord Jesus sets them free.",
    "From this original corruption, by which we are utterly indisposed, disabled, and made opposite to all good, and wholly inclined to all evil, proceed all actual transgressions.",
    "This corruption of nature, during this life, remains in those who are regenerated; and although it is pardoned and mortified through Christ, yet both it and its first motions are truly and properly sin.",
  ];

  R[7] = [
    "The distance between God and the creature is so great that, although reasonable creatures owe him obedience as their Creator, they could never have attained the reward of life except by some voluntary condescension on God's part, which he has been pleased to express by way of covenant.",
    "Moreover, since man brought himself under the curse of the law by his fall, it pleased the Lord to make a covenant of grace, in which he freely offers to sinners life and salvation by Jesus Christ, requiring of them faith in him that they may be saved, and promising to give his Holy Spirit to all those who are ordained to eternal life, to make them willing and able to believe.",
    "This covenant is revealed in the gospel — first to Adam in the promise of salvation by the seed of the woman, and afterward by further steps, until the full revelation of it was completed in the New Testament. It is founded in that eternal covenant transaction between the Father and the Son concerning the redemption of the elect; and it is alone by the grace of this covenant that all the descendants of fallen Adam who are saved obtain life and blessed immortality, since man is now utterly incapable of acceptance with God on the terms by which Adam stood in his state of innocence.",
  ];

  R[8] = [
    "It pleased God, in his eternal purpose, to choose and ordain the Lord Jesus, his only begotten Son, according to the covenant made between them both, to be the mediator between God and man; to be prophet, priest, and king; head and savior of the church; the heir of all things, and judge of the world. From all eternity God gave to him a people to be his seed, who would in time be redeemed, called, justified, sanctified, and glorified by him.",
    "The Son of God, the second person in the Holy Trinity, being very and eternal God — the brightness of the Father's glory, of one substance and equal with him — took upon himself man's nature, with all its essential properties and common infirmities, yet without sin. So two whole, perfect, and distinct natures were inseparably joined together in one person, without conversion, composition, or confusion; which person is very God and very man, yet one Christ, the only mediator between God and man.",
    "The Lord Jesus, in his human nature thus united to the divine, was sanctified and anointed with the Holy Spirit beyond measure, having in himself all the treasures of wisdom and knowledge — so that, being holy, harmless, undefiled, and full of grace and truth, he might be thoroughly furnished to execute the office of a mediator and surety, which he did not take upon himself but was called to by his Father.",
    "This office the Lord Jesus most willingly undertook; and to discharge it, he was made under the law, and perfectly fulfilled it, and underwent the punishment due to us, which we should have borne and suffered. He was made sin and a curse for us, enduring the most grievous sorrows in his soul and most painful sufferings in his body; was crucified and died, and remained in the state of the dead, yet saw no corruption. On the third day he arose from the dead with the same body in which he suffered, with which he also ascended into heaven, and there sits at the right hand of his Father interceding, and will return to judge men and angels at the end of the world.",
    "The Lord Jesus, by his perfect obedience and the sacrifice of himself, which he offered up to God through the eternal Spirit once for all, has fully satisfied the justice of God, procured reconciliation, and purchased an everlasting inheritance in the kingdom of heaven for all those whom the Father has given to him.",
    "Although the price of redemption was not actually paid by Christ until after his incarnation, yet its virtue, efficacy, and benefits were communicated to the elect in all ages, successively from the beginning of the world, in and by those promises, types, and sacrifices in which he was revealed and signified to be the seed of the woman who would bruise the serpent's head, and the Lamb slain from the foundation of the world; being the same yesterday, today, and forever.",
    "Christ, in the work of mediation, acts according to both natures, by each nature doing what is proper to it; yet, by reason of the unity of the person, what is proper to one nature is sometimes in Scripture attributed to the person under the name of the other nature.",
    "To all those for whom Christ has obtained eternal redemption, he certainly and effectually applies and communicates it; making intercession for them, uniting them to himself by his Spirit, revealing to them in and by the Word the mystery of salvation, persuading them to believe and obey, governing their hearts by his Word and Spirit, and overcoming all their enemies by his almighty power and wisdom — in such manner and ways as are most agreeable to his wonderful and unsearchable governance.",
    "This effectual application and communication of redemption is made to all those, and only those, for whom Christ has purchased it; he was given by the Father for them, made for a time under the law, and undertook and discharged everything required for their salvation.",
    "Although his obedience and satisfaction have a worth and value sufficient to redeem the whole world, yet, since the work of redemption is certainly applied and effectually communicated to none but the elect, it is appointed for them alone, and is freely vouchsafed to them out of God's free grace, that they might in no respect glory in themselves but in the Lord alone.",
  ];
})();
