/* Cornerstone — Reading text, chapters 25–32 (1689 LBCF, modern English rendering). */
(function () {
  const R = (window.READING = window.READING || {});

  R[25] = [
    "Marriage is to be between one man and one woman; nor is it lawful for any man to have more than one wife, nor for any woman to have more than one husband, at the same time.",
    "Marriage was ordained for the mutual help of husband and wife, for the increase of mankind with a legitimate offspring, and for the preventing of uncleanness.",
    "It is lawful for all sorts of people to marry who are able with judgment to give their consent; yet it is the duty of Christians to marry only in the Lord. Therefore those who profess the true religion should not marry with unbelievers or idolaters; nor should the godly be unequally yoked by marrying those who lead notoriously wicked lives or maintain damnable heresies.",
    "Marriage ought not to be within the degrees of consanguinity or affinity forbidden in the Word; nor can such incestuous marriages ever be made lawful, by any law of man or consent of parties, so that those persons may live together as husband and wife.",
  ];

  R[26] = [
    "The catholic or universal church, which (with respect to the internal work of the Spirit and the truth of grace) may be called invisible, consists of the whole number of the elect that have been, are, or shall be gathered into one, under Christ, the head; and is the spouse, the body, the fullness of him who fills all in all.",
    "All persons throughout the world, professing the faith of the gospel and obedience to God by Christ according to it, and not destroying their own profession by any errors that overthrow the foundation, or by unholiness of life, are and may be called visible saints; and of such persons all particular congregations ought to be constituted.",
    "The purest churches under heaven are subject to mixture and error; and some have so degenerated as to become no churches of Christ, but synagogues of Satan. Nevertheless, Christ always has had, and ever shall have, a kingdom in this world, to the end of it, of those who believe in him and profess his name.",
    "The Lord Jesus Christ is the head of the church, in whom, by the appointment of the Father, all power for the calling, institution, order, and government of the church is invested in a supreme and sovereign manner; neither can the Pope of Rome in any sense be head of it, but is that antichrist, that man of sin and son of perdition, who exalts himself in the church against Christ.",
    "In the execution of this power, the Lord Jesus calls to himself, out of the world, through the ministry of his Word and by his Spirit, those given to him by his Father, that they may walk before him in all the ways of obedience which he prescribes to them in his Word. Those thus called he commands to walk together in particular societies, or churches, for their mutual edification and the due performance of that public worship which he requires of them in the world.",
    "The members of these churches are saints by calling, visibly manifesting and evidencing, in and by their profession and walk, their obedience to the call of Christ; and they willingly consent to walk together, according to the appointment of Christ, giving themselves up to the Lord and to one another, by the will of God, in professed subjection to the ordinances of the gospel.",
    "To each of these churches thus gathered, the Lord has given all that power and authority which is in any way needful for carrying on the order in worship and discipline which he has instituted for them to observe, with commands and rules for the due and right exercising of that power.",
    "A particular church, gathered and completely organized according to the mind of Christ, consists of officers and members; and the officers appointed by Christ, to be chosen and set apart by the church for the peculiar administration of ordinances and execution of the power or duty entrusted to them, to be continued to the end of the world, are bishops (or elders) and deacons.",
    "The way appointed by Christ for the calling of any person, fitted and gifted by the Holy Spirit, to the office of bishop or elder, is that he be chosen by the common vote of the church itself, and solemnly set apart by fasting and prayer, with the laying on of hands of the eldership, if any are already in the church; for a deacon, that he be chosen by the like vote and set apart by prayer and the like laying on of hands.",
    "The work of pastors being to attend constantly to the service of Christ in his churches, in the ministry of the Word and prayer, watching for the souls of those of whom they must give an account; it is the duty of the churches to whom they minister not only to give them all due respect, but also to share with them of all their good things according to their ability, that they may have a comfortable supply, without being entangled in secular affairs, and may also exercise hospitality toward others; for this is required by the law of nature and by the express order of our Lord Jesus, who has ordained that those who preach the gospel should live of the gospel.",
    "Although it is the duty of the bishops or pastors of the churches to be constant in preaching the Word, the work of preaching the Word is not so peculiarly confined to them that others also, gifted and fitted by the Holy Spirit for it, and approved and called by the church, may not and ought not to perform it.",
    "Since all believers are bound to join themselves to particular churches when and where they have opportunity, so all who are admitted to the privileges of a church are also under the censures and government of it, according to the rule of Christ.",
    "No church members, upon any offense taken by them, having performed their duty toward the person they are offended at, ought to disturb any church order, or absent themselves from the assemblies of the church or the administration of any ordinances, on account of such offense; but they are to wait upon Christ in the further proceedings of the church.",
    "As each church, and all the members of it, are bound to pray continually for the good and prosperity of all the churches of Christ in all places, and to further everyone within the bounds of their places and callings in the exercise of their gifts and graces; so the churches, when planted by the providence of God so as they may enjoy opportunity for it, ought to hold communion among themselves, for their peace, increase of love, and mutual edification.",
    "In cases of difficulty or difference, whether in point of doctrine or administration, in which the churches in general are concerned, or any single church in its peace, union, and edification, or any member is injured by proceedings in censures not agreeable to truth and order: it is according to the mind of Christ that many churches holding communion together should meet, by their messengers, to consider and give their advice about the matter in difference, to be reported to all the churches concerned. Yet these messengers are not entrusted with any church power properly so called, nor with any jurisdiction over the churches themselves, nor to impose their determination on the churches or their officers.",
  ];

  R[27] = [
    "All saints who are united to Jesus Christ their head, by his Spirit and by faith — although they are not thereby made one person with him — have fellowship in his graces, sufferings, death, resurrection, and glory; and, being united to one another in love, they have communion in each other's gifts and graces, and are obliged to perform such duties, public and private, in an orderly way, as conduce to their mutual good, both in the inward and the outward man.",
    "Saints, by their profession, are bound to maintain a holy fellowship and communion in the worship of God, and in performing such other spiritual services as tend to their mutual edification, as well as in relieving each other in outward things according to their various abilities and necessities. This communion, according to the rule of the gospel, though especially to be exercised among those of the household of faith, is yet to be extended to all those who in every place call upon the name of the Lord Jesus, as God offers opportunity.",
  ];

  R[28] = [
    "Baptism and the Lord's Supper are ordinances of positive and sovereign institution, appointed by the Lord Jesus, the only lawgiver, to be continued in his church to the end of the world.",
    "These holy appointments are to be administered by those only who are qualified and called to do so, according to the commission of Christ.",
  ];

  R[29] = [
    "Baptism is an ordinance of the New Testament, ordained by Jesus Christ, to be to the person baptized a sign of his fellowship with Christ in his death and resurrection; of his being engrafted into him; of the remission of sins; and of his giving up himself to God, through Jesus Christ, to live and walk in newness of life.",
    "Those who actually profess repentance toward God, and faith in and obedience to our Lord Jesus Christ, are the only proper subjects of this ordinance.",
    "The outward element to be used in this ordinance is water, in which the person is to be baptized in the name of the Father, and of the Son, and of the Holy Spirit.",
    "Immersion, or the dipping of the person in water, is necessary to the due administration of this ordinance.",
  ];

  R[30] = [
    "The Supper of the Lord Jesus was instituted by him the same night in which he was betrayed, to be observed in his churches to the end of the world, for the perpetual remembrance and showing forth of the sacrifice of himself in his death; the confirmation of the faith of believers in all the benefits of it; their spiritual nourishment and growth in him; and their further engagement in and to all duties which they owe to him; and to be a bond and pledge of their communion with him and with each other.",
    "In this ordinance Christ is not offered up to his Father, nor any real sacrifice made at all for the remission of sin of the living or the dead; but it is only a memorial of that one offering up of himself, by himself, upon the cross, once for all, and a spiritual offering of all possible praise to God for it. So the sacrifice of the mass is most abominable, and injurious to Christ's own one sacrifice, the only propitiation for all the sins of the elect.",
    "The Lord Jesus has, in this ordinance, appointed his ministers to pray and bless the elements of bread and wine, thereby setting them apart from a common to a holy use, to take and break the bread, to take the cup, and (they themselves partaking) to give both to the communicants.",
    "The denial of the cup to the people, worshiping the elements, lifting them up or carrying them about for adoration, and reserving them for any pretended religious use, are all contrary to the nature of this ordinance and to the institution of Christ.",
    "The outward elements in this ordinance, duly set apart to the use ordained by Christ, have such relation to him crucified that, truly yet sacramentally only, they are sometimes called by the names of the things they represent — the body and blood of Christ; although, in substance and nature, they still remain truly and only bread and wine, as they were before.",
    "The doctrine which maintains a change of the substance of bread and wine into the substance of Christ's body and blood (commonly called transubstantiation), by the consecration of a priest or by any other way, is repugnant not to Scripture alone, but even to common sense and reason; it overthrows the nature of the ordinance, and has been the cause of manifold superstitions and gross idolatries.",
    "Worthy receivers, outwardly partaking of the visible elements in this ordinance, do then also inwardly, by faith, really and indeed — yet not carnally and corporally, but spiritually — receive and feed upon Christ crucified, and all the benefits of his death. The body and blood of Christ are then not corporally or carnally, but spiritually, present to the faith of believers in that ordinance, as the elements themselves are to their outward senses.",
  ];

  R[31] = [
    "The bodies of men after death return to dust, and see corruption; but their souls, which neither die nor sleep, having an immortal subsistence, immediately return to God who gave them. The souls of the righteous, being then made perfect in holiness, are received into paradise, where they are with Christ and behold the face of God in light and glory, waiting for the full redemption of their bodies; and the souls of the wicked are cast into hell, where they remain in torment and utter darkness, reserved to the judgment of the great day. Besides these two places for souls separated from their bodies, the Scripture acknowledges none.",
    "At the last day, those of the saints who are found alive shall not sleep, but be changed; and all the dead shall be raised up with the very same bodies, and no other, although with different qualities, which shall be united again to their souls forever.",
    "The bodies of the unjust shall, by the power of Christ, be raised to dishonor; the bodies of the just, by his Spirit, to honor, and be made conformable to his own glorious body.",
  ];

  R[32] = [
    "God has appointed a day in which he will judge the world in righteousness by Jesus Christ, to whom all power and judgment is given by the Father. In that day not only the apostate angels shall be judged, but all persons who have ever lived upon the earth shall appear before the tribunal of Christ, to give an account of their thoughts, words, and deeds, and to receive according to what they have done in the body, whether good or evil.",
    "The purpose of God's appointing this day is the manifestation of the glory of his mercy in the eternal salvation of the elect, and of his justice in the eternal damnation of the reprobate; for then the righteous shall go into everlasting life, and receive that fullness of joy and glory in the presence of the Lord; but the wicked, who do not know God and do not obey the gospel of Jesus Christ, shall be cast into eternal torments, and punished with everlasting destruction from the presence of the Lord.",
    "As Christ would have us to be certainly persuaded that there shall be a day of judgment, both to deter all men from sin and for the greater consolation of the godly in their adversity; so he will have that day unknown to men, that they may shake off all carnal security and be always watchful, because they do not know at what hour the Lord will come, and may ever be prepared to say, \u201cCome, Lord Jesus; come quickly.\u201d Amen.",
  ];
})();
