/* Cornerstone — Reading text, chapters 17–24 (1689 LBCF, modern English rendering). */
(function () {
  const R = (window.READING = window.READING || {});

  R[17] = [
    "Those whom God has accepted in the Beloved, effectually called and sanctified by his Spirit, and given the precious faith of his elect, can neither totally nor finally fall from the state of grace, but shall certainly persevere in it to the end, and be eternally saved; for the gifts and callings of God are without repentance, and from this he still begets and nourishes in them faith, repentance, love, joy, hope, and all the graces of the Spirit unto immortality.",
    "This perseverance of the saints depends not upon their own free will, but upon the immutability of the decree of election, flowing from the free and unchangeable love of God the Father; upon the efficacy of the merit and intercession of Jesus Christ, and union with him; the oath of God; the abiding of his Spirit and the seed of God within them; and the nature of the covenant of grace — from all of which arises also its certainty and infallibility.",
    "Yet they may, through the temptations of Satan and of the world, the prevalence of corruption remaining in them, and the neglect of the means of their preservation, fall into grievous sins and continue in them for a time; whereby they incur God's displeasure, grieve his Holy Spirit, have their graces and comforts impaired, their hearts hardened and their consciences wounded, hurt and scandalize others, and bring temporal judgments upon themselves; yet they shall renew their repentance and be preserved, through faith in Christ Jesus, to the end.",
  ];

  R[18] = [
    "Although temporary believers, and other unregenerate men, may vainly deceive themselves with false hopes and carnal presumptions of being in the favor of God and in a state of salvation — which hope of theirs shall perish — yet those who truly believe in the Lord Jesus, and love him in sincerity, endeavoring to walk in all good conscience before him, may in this life be certainly assured that they are in the state of grace, and may rejoice in the hope of the glory of God, a hope that shall never make them ashamed.",
    "This certainty is not a bare conjectural and probable persuasion grounded on a fallible hope, but an infallible assurance of faith, founded on the blood and righteousness of Christ revealed in the gospel; and also upon the inward evidence of those graces of the Spirit to which the promises are made, and on the testimony of the Spirit of adoption, witnessing with our spirits that we are the children of God; and, as a fruit of it, keeping the heart both humble and holy.",
    "This infallible assurance does not so belong to the essence of faith but that a true believer may wait long, and conflict with many difficulties, before he is a partaker of it; yet, being enabled by the Spirit to know the things freely given to him by God, he may, without extraordinary revelation, in the right use of means, attain it. Therefore it is the duty of everyone to be diligent to make his calling and election sure, that his heart may be enlarged in peace and joy in the Holy Spirit, in love and thankfulness to God, and in strength and cheerfulness in the duties of obedience.",
    "The assurance of true believers may be shaken, diminished, and intermitted in various ways — by negligence in preserving it; by falling into some special sin which wounds the conscience and grieves the Spirit; by some sudden or vehement temptation; or by God's withdrawing the light of his countenance, allowing even those who fear him to walk in darkness and have no light. Yet they are never utterly destitute of that seed of God, and life of faith, that love of Christ and of the brethren, that sincerity of heart and conscience of duty, out of which, by the operation of the Spirit, this assurance may in due time be revived, and by which, in the meantime, they are preserved from utter despair.",
  ];

  R[19] = [
    "God gave to Adam a law of universal obedience written in his heart, and a particular precept of not eating the fruit of the tree of the knowledge of good and evil; by which he bound him, and all his posterity, to personal, entire, exact, and perpetual obedience; promised life upon the keeping of it, and threatened death upon the breaking of it; and endued him with power and ability to keep it.",
    "The same law that was first written in the heart of man continued to be a perfect rule of righteousness after the fall, and was delivered by God upon Mount Sinai in ten commandments, written in two tables — the first four containing our duty toward God, and the other six our duty toward man.",
    "Besides this law, commonly called the moral law, God was pleased to give to the people of Israel ceremonial laws, containing several typical ordinances — partly of worship, prefiguring Christ, his graces, actions, sufferings, and benefits; and partly holding forth various instructions of moral duties. All these ceremonial laws, being appointed only to the time of reformation, are, by Jesus Christ the true Messiah and only lawgiver, abrogated and taken away.",
    "To them also he gave various judicial laws, which expired together with the state of that people; these oblige no one now by virtue of that institution, their general equity only being of moral use.",
    "The moral law forever binds everyone — justified persons as well as others — to obedience to it; and that not only in regard to the matter contained in it, but also in respect of the authority of God the Creator, who gave it. Nor does Christ in the gospel in any way dissolve this, but considerably strengthens this obligation.",
  ];

  R[20] = [
    "The covenant of works being broken by sin and made unprofitable for life, God was pleased to give the promise of Christ, the seed of the woman, as the means of calling the elect, and of begetting in them faith and repentance. In this promise the gospel, as to its substance, was revealed, and is therein effectual for the conversion and salvation of sinners.",
    "This promise of Christ, and salvation by him, is revealed only by the Word of God. Neither do the works of creation or providence, with the light of nature, make discovery of Christ, or of grace by him, even in a general or obscure way; much less can men who lack the revelation of him by the promise, or gospel, attain saving faith or repentance.",
    "The revelation of the gospel to sinners — made in various times and different ways, with the addition of promises and precepts for the obedience required in it, as to the nations and persons to whom it is granted — is merely of the sovereign will and good pleasure of God; it is not annexed by virtue of any promise to the good use of men's natural abilities. Therefore in all ages the preaching of the gospel has been granted to persons and nations in great variety, according to the counsel of the will of God.",
    "Although the gospel is the only outward means of revealing Christ and saving grace, and is, as such, abundantly sufficient for that purpose; yet, so that men who are dead in trespasses may be born again, made alive, or regenerated, it is also necessary that there be an effectual, irresistible work of the Holy Spirit upon the whole soul, to produce in them a new spiritual life; without which no other means will effect their conversion to God.",
  ];

  R[21] = [
    "The liberty which Christ has purchased for believers under the gospel consists in their freedom from the guilt of sin, the condemning wrath of God, and the rigor and curse of the law; and in their being delivered from this present evil world, bondage to Satan, the dominion of sin, the evil of afflictions, the fear and sting of death, the victory of the grave, and everlasting damnation; as also in their free access to God, and their yielding obedience to him, not out of slavish fear, but a child-like love and willing mind. Under the New Testament the liberty of Christians is further enlarged — in freedom from the yoke of the ceremonial law, in greater boldness of access to the throne of grace, and in fuller communications of the free Spirit of God.",
    "God alone is Lord of the conscience, and has left it free from the doctrines and commandments of men which are in anything contrary to his Word, or not contained in it. So to believe such doctrines, or to obey such commands out of conscience, is to betray true liberty of conscience; and the requiring of an implicit faith and an absolute and blind obedience is to destroy liberty of conscience, and reason also.",
    "Those who, upon pretense of Christian liberty, practice any sin or cherish any lust, thereby destroy the very purpose of Christian liberty — which is that, being delivered out of the hands of all our enemies, we might serve the Lord without fear, in holiness and righteousness before him, all the days of our life.",
  ];

  R[22] = [
    "The light of nature shows that there is a God, who has lordship and sovereignty over all; is just, good, and does good to all; and is therefore to be feared, loved, praised, called upon, trusted in, and served with all the heart, soul, and might. But the acceptable way of worshiping the true God is instituted by himself, and so limited by his own revealed will, that he may not be worshiped according to the imaginations and devices of men, nor the suggestions of Satan, under any visible representation, or any other way not prescribed in the Holy Scripture.",
    "Religious worship is to be given to God the Father, Son, and Holy Spirit, and to him alone; not to angels, saints, or any other creature; and since the fall, not without a mediator, nor in the mediation of any other but Christ alone.",
    "Prayer, with thanksgiving, being one part of natural worship, is required by God of all men; and that it may be accepted, it is to be made in the name of the Son, by the help of the Spirit, according to his will; with understanding, reverence, humility, fervency, faith, love, and perseverance; and when with others, in a known tongue.",
    "Prayer is to be made for things lawful, and for all sorts of people living, or who shall live hereafter; but not for the dead, nor for those of whom it may be known that they have sinned the sin unto death.",
    "The reading of the Scriptures, preaching and hearing the Word of God, teaching and admonishing one another in psalms, hymns, and spiritual songs, singing with grace in our hearts to the Lord; as also the administration of baptism and the Lord's Supper, are all parts of the religious worship of God, to be performed in obedience to him, with understanding, faith, reverence, and godly fear.",
    "Neither prayer nor any other part of religious worship is now, under the gospel, tied to or made more acceptable by any place in which it is performed; but God is to be worshiped everywhere in spirit and in truth — daily in private families, in secret by each one alone, and more solemnly in the public assemblies, which are not to be carelessly or willfully neglected or forsaken when God, by his Word or providence, calls to them.",
    "As it is the law of nature that, in general, a proportion of time be set apart for the worship of God, so by his Word, in a positive, moral, and perpetual commandment binding all men in all ages, he has particularly appointed one day in seven for a Sabbath to be kept holy to him. From the beginning of the world to the resurrection of Christ this was the last day of the week; and from the resurrection of Christ it was changed to the first day of the week, called the Lord's Day, to be continued to the end of the world as the Christian Sabbath.",
    "The Sabbath is kept holy to the Lord when men, after a due preparing of their hearts and ordering their common affairs beforehand, observe a holy rest all the day from their own works, words, and thoughts about their worldly employments and recreations, and are taken up the whole time in the public and private exercises of his worship, and in the duties of necessity and mercy.",
  ];

  R[23] = [
    "A lawful oath is a part of religious worship, in which the person swearing in truth, righteousness, and judgment solemnly calls God to witness what he asserts or promises, and to judge him according to the truth or falsehood of what he swears.",
    "The name of God only is that by which men ought to swear; and in swearing by it they ought to use the utmost holy fear and reverence. Therefore to swear vainly or rashly by that glorious and dreadful name, or to swear at all by any other thing, is sinful and to be abhorred. Yet, in matters of weight and moment, an oath is warranted by the Word of God for the confirmation of truth and the ending of all strife; and so a lawful oath, imposed by lawful authority in such matters, ought to be taken.",
    "Whoever takes an oath warranted by the Word of God ought duly to consider the weight of so solemn an act, and in it to affirm nothing but what he knows to be the truth; for by rash, false, and vain oaths the Lord is provoked, and because of them this land mourns.",
    "A vow, which is to be made to God alone, is of the like nature with a promissory oath, and ought to be made with the same religious care, and performed with the same faithfulness.",
  ];

  R[24] = [
    "God, the supreme Lord and King of all the world, has ordained civil magistrates to be under him, over the people, for his own glory and the public good; and to this end has armed them with the power of the sword, for the defense and encouragement of those who do good, and for the punishment of evildoers.",
    "It is lawful for Christians to accept and execute the office of a magistrate when called to it; in the performance of which office they ought especially to maintain justice and peace, according to the wholesome laws of each kingdom and commonwealth; and so, under the New Testament, they may lawfully now wage war upon just and necessary occasions.",
    "It is the duty of people to pray for magistrates, to honor their persons, to pay them taxes and other dues, to obey their lawful commands, and to be subject to their authority for conscience' sake. Unbelief or difference in religion does not make void the magistrate's just and legal authority, nor free the people from their due obedience to him.",
  ];
})();
