/* Cornerstone — baked-in ESV verse store.
   Keyed by the exact citation string used in app/read-meta.js (semicolon-split),
   e.g. "2 Timothy 3:15-17". Each value is { verses: [{ n, t }], source: "esv" }.

   This file is GENERATED by verse-harvester.html (run once on the live site,
   which is the only origin allowed to read the Cloudflare Worker). Until it is
   populated, the app falls back to the live Worker fetch, then AI.

   To (re)generate: open  verse-harvester.html  on https://codekaylem.github.io/...
   click "Fetch all verses", then "Download verses.js" and commit the result here. */
window.VERSES = window.VERSES || {};
